/*
 * LumoAuth API
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lumoauth.client.api;

import io.lumoauth.client.ApiCallback;
import io.lumoauth.client.ApiClient;
import io.lumoauth.client.ApiException;
import io.lumoauth.client.ApiResponse;
import io.lumoauth.client.Configuration;
import io.lumoauth.client.Pair;
import io.lumoauth.client.ProgressRequestBody;
import io.lumoauth.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.lumoauth.client.model.AdminSocialProvidersAvailableResponse;
import io.lumoauth.client.model.AdminSocialProvidersCallbackUrlsResponse;
import io.lumoauth.client.model.AdminSocialProvidersCreateResponse;
import io.lumoauth.client.model.AdminSocialProvidersGetResponse;
import io.lumoauth.client.model.AdminSocialProvidersListResponse;
import io.lumoauth.client.model.MessageResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AdminIdentityProvidersApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AdminIdentityProvidersApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AdminIdentityProvidersApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for adminSocialProvidersAvailable
     * @param orgId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider types </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSocialProvidersAvailableCall(@javax.annotation.Nonnull String orgId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/orgs/{orgId}/api/v1/admin/social-providers/available"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call adminSocialProvidersAvailableValidateBeforeCall(@javax.annotation.Nonnull String orgId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling adminSocialProvidersAvailable(Async)");
        }

        return adminSocialProvidersAvailableCall(orgId, _callback);

    }

    /**
     * List the available social login provider types
     * 
     * @param orgId  (required)
     * @return AdminSocialProvidersAvailableResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider types </td><td>  -  </td></tr>
     </table>
     */
    public AdminSocialProvidersAvailableResponse adminSocialProvidersAvailable(@javax.annotation.Nonnull String orgId) throws ApiException {
        ApiResponse<AdminSocialProvidersAvailableResponse> localVarResp = adminSocialProvidersAvailableWithHttpInfo(orgId);
        return localVarResp.getData();
    }

    /**
     * List the available social login provider types
     * 
     * @param orgId  (required)
     * @return ApiResponse&lt;AdminSocialProvidersAvailableResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider types </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AdminSocialProvidersAvailableResponse> adminSocialProvidersAvailableWithHttpInfo(@javax.annotation.Nonnull String orgId) throws ApiException {
        okhttp3.Call localVarCall = adminSocialProvidersAvailableValidateBeforeCall(orgId, null);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersAvailableResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List the available social login provider types (asynchronously)
     * 
     * @param orgId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider types </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSocialProvidersAvailableAsync(@javax.annotation.Nonnull String orgId, final ApiCallback<AdminSocialProvidersAvailableResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = adminSocialProvidersAvailableValidateBeforeCall(orgId, _callback);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersAvailableResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for adminSocialProvidersCallbackUrls
     * @param orgId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Map of provider name to callback URL </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSocialProvidersCallbackUrlsCall(@javax.annotation.Nonnull String orgId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/orgs/{orgId}/api/v1/admin/social-providers/callback-urls"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call adminSocialProvidersCallbackUrlsValidateBeforeCall(@javax.annotation.Nonnull String orgId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling adminSocialProvidersCallbackUrls(Async)");
        }

        return adminSocialProvidersCallbackUrlsCall(orgId, _callback);

    }

    /**
     * Get the OAuth callback URL of every configured provider
     * 
     * @param orgId  (required)
     * @return AdminSocialProvidersCallbackUrlsResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Map of provider name to callback URL </td><td>  -  </td></tr>
     </table>
     */
    public AdminSocialProvidersCallbackUrlsResponse adminSocialProvidersCallbackUrls(@javax.annotation.Nonnull String orgId) throws ApiException {
        ApiResponse<AdminSocialProvidersCallbackUrlsResponse> localVarResp = adminSocialProvidersCallbackUrlsWithHttpInfo(orgId);
        return localVarResp.getData();
    }

    /**
     * Get the OAuth callback URL of every configured provider
     * 
     * @param orgId  (required)
     * @return ApiResponse&lt;AdminSocialProvidersCallbackUrlsResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Map of provider name to callback URL </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AdminSocialProvidersCallbackUrlsResponse> adminSocialProvidersCallbackUrlsWithHttpInfo(@javax.annotation.Nonnull String orgId) throws ApiException {
        okhttp3.Call localVarCall = adminSocialProvidersCallbackUrlsValidateBeforeCall(orgId, null);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersCallbackUrlsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get the OAuth callback URL of every configured provider (asynchronously)
     * 
     * @param orgId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Map of provider name to callback URL </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSocialProvidersCallbackUrlsAsync(@javax.annotation.Nonnull String orgId, final ApiCallback<AdminSocialProvidersCallbackUrlsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = adminSocialProvidersCallbackUrlsValidateBeforeCall(orgId, _callback);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersCallbackUrlsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for adminSocialProvidersCreate
     * @param orgId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created provider (detailed; secrets redacted) </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Provider already configured </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSocialProvidersCreateCall(@javax.annotation.Nonnull String orgId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/orgs/{orgId}/api/v1/admin/social-providers"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call adminSocialProvidersCreateValidateBeforeCall(@javax.annotation.Nonnull String orgId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling adminSocialProvidersCreate(Async)");
        }

        return adminSocialProvidersCreateCall(orgId, _callback);

    }

    /**
     * Create a social login provider
     * 
     * @param orgId  (required)
     * @return AdminSocialProvidersCreateResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created provider (detailed; secrets redacted) </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Provider already configured </td><td>  -  </td></tr>
     </table>
     */
    public AdminSocialProvidersCreateResponse adminSocialProvidersCreate(@javax.annotation.Nonnull String orgId) throws ApiException {
        ApiResponse<AdminSocialProvidersCreateResponse> localVarResp = adminSocialProvidersCreateWithHttpInfo(orgId);
        return localVarResp.getData();
    }

    /**
     * Create a social login provider
     * 
     * @param orgId  (required)
     * @return ApiResponse&lt;AdminSocialProvidersCreateResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created provider (detailed; secrets redacted) </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Provider already configured </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AdminSocialProvidersCreateResponse> adminSocialProvidersCreateWithHttpInfo(@javax.annotation.Nonnull String orgId) throws ApiException {
        okhttp3.Call localVarCall = adminSocialProvidersCreateValidateBeforeCall(orgId, null);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersCreateResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a social login provider (asynchronously)
     * 
     * @param orgId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created provider (detailed; secrets redacted) </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Provider already configured </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSocialProvidersCreateAsync(@javax.annotation.Nonnull String orgId, final ApiCallback<AdminSocialProvidersCreateResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = adminSocialProvidersCreateValidateBeforeCall(orgId, _callback);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersCreateResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for adminSocialProvidersDelete
     * @param orgId  (required)
     * @param providerId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Deleted </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSocialProvidersDeleteCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/orgs/{orgId}/api/v1/admin/social-providers/{providerId}"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()))
            .replace("{" + "providerId" + "}", localVarApiClient.escapeString(providerId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call adminSocialProvidersDeleteValidateBeforeCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling adminSocialProvidersDelete(Async)");
        }

        // verify the required parameter 'providerId' is set
        if (providerId == null) {
            throw new ApiException("Missing the required parameter 'providerId' when calling adminSocialProvidersDelete(Async)");
        }

        return adminSocialProvidersDeleteCall(orgId, providerId, _callback);

    }

    /**
     * Delete a social login provider
     * 
     * @param orgId  (required)
     * @param providerId  (required)
     * @return MessageResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Deleted </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public MessageResponse adminSocialProvidersDelete(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId) throws ApiException {
        ApiResponse<MessageResponse> localVarResp = adminSocialProvidersDeleteWithHttpInfo(orgId, providerId);
        return localVarResp.getData();
    }

    /**
     * Delete a social login provider
     * 
     * @param orgId  (required)
     * @param providerId  (required)
     * @return ApiResponse&lt;MessageResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Deleted </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<MessageResponse> adminSocialProvidersDeleteWithHttpInfo(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId) throws ApiException {
        okhttp3.Call localVarCall = adminSocialProvidersDeleteValidateBeforeCall(orgId, providerId, null);
        Type localVarReturnType = new TypeToken<MessageResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete a social login provider (asynchronously)
     * 
     * @param orgId  (required)
     * @param providerId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Deleted </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSocialProvidersDeleteAsync(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId, final ApiCallback<MessageResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = adminSocialProvidersDeleteValidateBeforeCall(orgId, providerId, _callback);
        Type localVarReturnType = new TypeToken<MessageResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for adminSocialProvidersDisable
     * @param orgId  (required)
     * @param providerId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider disabled (summary fields only) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSocialProvidersDisableCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/orgs/{orgId}/api/v1/admin/social-providers/{providerId}/disable"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()))
            .replace("{" + "providerId" + "}", localVarApiClient.escapeString(providerId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call adminSocialProvidersDisableValidateBeforeCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling adminSocialProvidersDisable(Async)");
        }

        // verify the required parameter 'providerId' is set
        if (providerId == null) {
            throw new ApiException("Missing the required parameter 'providerId' when calling adminSocialProvidersDisable(Async)");
        }

        return adminSocialProvidersDisableCall(orgId, providerId, _callback);

    }

    /**
     * Disable a social login provider
     * 
     * @param orgId  (required)
     * @param providerId  (required)
     * @return AdminSocialProvidersCreateResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider disabled (summary fields only) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public AdminSocialProvidersCreateResponse adminSocialProvidersDisable(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId) throws ApiException {
        ApiResponse<AdminSocialProvidersCreateResponse> localVarResp = adminSocialProvidersDisableWithHttpInfo(orgId, providerId);
        return localVarResp.getData();
    }

    /**
     * Disable a social login provider
     * 
     * @param orgId  (required)
     * @param providerId  (required)
     * @return ApiResponse&lt;AdminSocialProvidersCreateResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider disabled (summary fields only) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AdminSocialProvidersCreateResponse> adminSocialProvidersDisableWithHttpInfo(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId) throws ApiException {
        okhttp3.Call localVarCall = adminSocialProvidersDisableValidateBeforeCall(orgId, providerId, null);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersCreateResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Disable a social login provider (asynchronously)
     * 
     * @param orgId  (required)
     * @param providerId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider disabled (summary fields only) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSocialProvidersDisableAsync(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId, final ApiCallback<AdminSocialProvidersCreateResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = adminSocialProvidersDisableValidateBeforeCall(orgId, providerId, _callback);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersCreateResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for adminSocialProvidersEnable
     * @param orgId  (required)
     * @param providerId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider enabled (summary fields only) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSocialProvidersEnableCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/orgs/{orgId}/api/v1/admin/social-providers/{providerId}/enable"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()))
            .replace("{" + "providerId" + "}", localVarApiClient.escapeString(providerId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call adminSocialProvidersEnableValidateBeforeCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling adminSocialProvidersEnable(Async)");
        }

        // verify the required parameter 'providerId' is set
        if (providerId == null) {
            throw new ApiException("Missing the required parameter 'providerId' when calling adminSocialProvidersEnable(Async)");
        }

        return adminSocialProvidersEnableCall(orgId, providerId, _callback);

    }

    /**
     * Enable a social login provider
     * 
     * @param orgId  (required)
     * @param providerId  (required)
     * @return AdminSocialProvidersCreateResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider enabled (summary fields only) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public AdminSocialProvidersCreateResponse adminSocialProvidersEnable(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId) throws ApiException {
        ApiResponse<AdminSocialProvidersCreateResponse> localVarResp = adminSocialProvidersEnableWithHttpInfo(orgId, providerId);
        return localVarResp.getData();
    }

    /**
     * Enable a social login provider
     * 
     * @param orgId  (required)
     * @param providerId  (required)
     * @return ApiResponse&lt;AdminSocialProvidersCreateResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider enabled (summary fields only) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AdminSocialProvidersCreateResponse> adminSocialProvidersEnableWithHttpInfo(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId) throws ApiException {
        okhttp3.Call localVarCall = adminSocialProvidersEnableValidateBeforeCall(orgId, providerId, null);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersCreateResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Enable a social login provider (asynchronously)
     * 
     * @param orgId  (required)
     * @param providerId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider enabled (summary fields only) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSocialProvidersEnableAsync(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId, final ApiCallback<AdminSocialProvidersCreateResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = adminSocialProvidersEnableValidateBeforeCall(orgId, providerId, _callback);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersCreateResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for adminSocialProvidersGet
     * @param orgId  (required)
     * @param providerId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider (detailed; secrets redacted) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSocialProvidersGetCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/orgs/{orgId}/api/v1/admin/social-providers/{providerId}"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()))
            .replace("{" + "providerId" + "}", localVarApiClient.escapeString(providerId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call adminSocialProvidersGetValidateBeforeCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling adminSocialProvidersGet(Async)");
        }

        // verify the required parameter 'providerId' is set
        if (providerId == null) {
            throw new ApiException("Missing the required parameter 'providerId' when calling adminSocialProvidersGet(Async)");
        }

        return adminSocialProvidersGetCall(orgId, providerId, _callback);

    }

    /**
     * Get a social login provider
     * 
     * @param orgId  (required)
     * @param providerId  (required)
     * @return AdminSocialProvidersGetResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider (detailed; secrets redacted) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public AdminSocialProvidersGetResponse adminSocialProvidersGet(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId) throws ApiException {
        ApiResponse<AdminSocialProvidersGetResponse> localVarResp = adminSocialProvidersGetWithHttpInfo(orgId, providerId);
        return localVarResp.getData();
    }

    /**
     * Get a social login provider
     * 
     * @param orgId  (required)
     * @param providerId  (required)
     * @return ApiResponse&lt;AdminSocialProvidersGetResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider (detailed; secrets redacted) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AdminSocialProvidersGetResponse> adminSocialProvidersGetWithHttpInfo(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId) throws ApiException {
        okhttp3.Call localVarCall = adminSocialProvidersGetValidateBeforeCall(orgId, providerId, null);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersGetResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get a social login provider (asynchronously)
     * 
     * @param orgId  (required)
     * @param providerId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider (detailed; secrets redacted) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSocialProvidersGetAsync(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId, final ApiCallback<AdminSocialProvidersGetResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = adminSocialProvidersGetValidateBeforeCall(orgId, providerId, _callback);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersGetResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for adminSocialProvidersList
     * @param orgId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Providers (summary fields only) </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSocialProvidersListCall(@javax.annotation.Nonnull String orgId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/orgs/{orgId}/api/v1/admin/social-providers"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call adminSocialProvidersListValidateBeforeCall(@javax.annotation.Nonnull String orgId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling adminSocialProvidersList(Async)");
        }

        return adminSocialProvidersListCall(orgId, _callback);

    }

    /**
     * List social login providers
     * 
     * @param orgId  (required)
     * @return AdminSocialProvidersListResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Providers (summary fields only) </td><td>  -  </td></tr>
     </table>
     */
    public AdminSocialProvidersListResponse adminSocialProvidersList(@javax.annotation.Nonnull String orgId) throws ApiException {
        ApiResponse<AdminSocialProvidersListResponse> localVarResp = adminSocialProvidersListWithHttpInfo(orgId);
        return localVarResp.getData();
    }

    /**
     * List social login providers
     * 
     * @param orgId  (required)
     * @return ApiResponse&lt;AdminSocialProvidersListResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Providers (summary fields only) </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AdminSocialProvidersListResponse> adminSocialProvidersListWithHttpInfo(@javax.annotation.Nonnull String orgId) throws ApiException {
        okhttp3.Call localVarCall = adminSocialProvidersListValidateBeforeCall(orgId, null);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersListResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List social login providers (asynchronously)
     * 
     * @param orgId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Providers (summary fields only) </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSocialProvidersListAsync(@javax.annotation.Nonnull String orgId, final ApiCallback<AdminSocialProvidersListResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = adminSocialProvidersListValidateBeforeCall(orgId, _callback);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersListResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for adminSocialProvidersTypes
     * @param orgId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider types </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSocialProvidersTypesCall(@javax.annotation.Nonnull String orgId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/orgs/{orgId}/api/v1/admin/social-providers/types"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call adminSocialProvidersTypesValidateBeforeCall(@javax.annotation.Nonnull String orgId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling adminSocialProvidersTypes(Async)");
        }

        return adminSocialProvidersTypesCall(orgId, _callback);

    }

    /**
     * List the available social login provider types
     * 
     * @param orgId  (required)
     * @return AdminSocialProvidersAvailableResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider types </td><td>  -  </td></tr>
     </table>
     */
    public AdminSocialProvidersAvailableResponse adminSocialProvidersTypes(@javax.annotation.Nonnull String orgId) throws ApiException {
        ApiResponse<AdminSocialProvidersAvailableResponse> localVarResp = adminSocialProvidersTypesWithHttpInfo(orgId);
        return localVarResp.getData();
    }

    /**
     * List the available social login provider types
     * 
     * @param orgId  (required)
     * @return ApiResponse&lt;AdminSocialProvidersAvailableResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider types </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AdminSocialProvidersAvailableResponse> adminSocialProvidersTypesWithHttpInfo(@javax.annotation.Nonnull String orgId) throws ApiException {
        okhttp3.Call localVarCall = adminSocialProvidersTypesValidateBeforeCall(orgId, null);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersAvailableResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List the available social login provider types (asynchronously)
     * 
     * @param orgId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Provider types </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSocialProvidersTypesAsync(@javax.annotation.Nonnull String orgId, final ApiCallback<AdminSocialProvidersAvailableResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = adminSocialProvidersTypesValidateBeforeCall(orgId, _callback);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersAvailableResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for patchAdminSocialProvidersUpdate
     * @param orgId  (required)
     * @param providerId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Updated provider (detailed) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call patchAdminSocialProvidersUpdateCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/orgs/{orgId}/api/v1/admin/social-providers/{providerId}"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()))
            .replace("{" + "providerId" + "}", localVarApiClient.escapeString(providerId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call patchAdminSocialProvidersUpdateValidateBeforeCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling patchAdminSocialProvidersUpdate(Async)");
        }

        // verify the required parameter 'providerId' is set
        if (providerId == null) {
            throw new ApiException("Missing the required parameter 'providerId' when calling patchAdminSocialProvidersUpdate(Async)");
        }

        return patchAdminSocialProvidersUpdateCall(orgId, providerId, _callback);

    }

    /**
     * Update a social login provider
     * 
     * @param orgId  (required)
     * @param providerId  (required)
     * @return AdminSocialProvidersCreateResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Updated provider (detailed) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public AdminSocialProvidersCreateResponse patchAdminSocialProvidersUpdate(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId) throws ApiException {
        ApiResponse<AdminSocialProvidersCreateResponse> localVarResp = patchAdminSocialProvidersUpdateWithHttpInfo(orgId, providerId);
        return localVarResp.getData();
    }

    /**
     * Update a social login provider
     * 
     * @param orgId  (required)
     * @param providerId  (required)
     * @return ApiResponse&lt;AdminSocialProvidersCreateResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Updated provider (detailed) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AdminSocialProvidersCreateResponse> patchAdminSocialProvidersUpdateWithHttpInfo(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId) throws ApiException {
        okhttp3.Call localVarCall = patchAdminSocialProvidersUpdateValidateBeforeCall(orgId, providerId, null);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersCreateResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update a social login provider (asynchronously)
     * 
     * @param orgId  (required)
     * @param providerId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Updated provider (detailed) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Social login provider not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call patchAdminSocialProvidersUpdateAsync(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId, final ApiCallback<AdminSocialProvidersCreateResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = patchAdminSocialProvidersUpdateValidateBeforeCall(orgId, providerId, _callback);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersCreateResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for putAdminSocialProvidersUpdate
     * @param orgId  (required)
     * @param providerId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Updated provider (detailed) </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> Provider did not exist and was created </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call putAdminSocialProvidersUpdateCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/orgs/{orgId}/api/v1/admin/social-providers/{providerId}"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()))
            .replace("{" + "providerId" + "}", localVarApiClient.escapeString(providerId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call putAdminSocialProvidersUpdateValidateBeforeCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling putAdminSocialProvidersUpdate(Async)");
        }

        // verify the required parameter 'providerId' is set
        if (providerId == null) {
            throw new ApiException("Missing the required parameter 'providerId' when calling putAdminSocialProvidersUpdate(Async)");
        }

        return putAdminSocialProvidersUpdateCall(orgId, providerId, _callback);

    }

    /**
     * Create or replace a social login provider
     * 
     * @param orgId  (required)
     * @param providerId  (required)
     * @return AdminSocialProvidersCreateResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Updated provider (detailed) </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> Provider did not exist and was created </td><td>  -  </td></tr>
     </table>
     */
    public AdminSocialProvidersCreateResponse putAdminSocialProvidersUpdate(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId) throws ApiException {
        ApiResponse<AdminSocialProvidersCreateResponse> localVarResp = putAdminSocialProvidersUpdateWithHttpInfo(orgId, providerId);
        return localVarResp.getData();
    }

    /**
     * Create or replace a social login provider
     * 
     * @param orgId  (required)
     * @param providerId  (required)
     * @return ApiResponse&lt;AdminSocialProvidersCreateResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Updated provider (detailed) </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> Provider did not exist and was created </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AdminSocialProvidersCreateResponse> putAdminSocialProvidersUpdateWithHttpInfo(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId) throws ApiException {
        okhttp3.Call localVarCall = putAdminSocialProvidersUpdateValidateBeforeCall(orgId, providerId, null);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersCreateResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create or replace a social login provider (asynchronously)
     * 
     * @param orgId  (required)
     * @param providerId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Updated provider (detailed) </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> Provider did not exist and was created </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call putAdminSocialProvidersUpdateAsync(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String providerId, final ApiCallback<AdminSocialProvidersCreateResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = putAdminSocialProvidersUpdateValidateBeforeCall(orgId, providerId, _callback);
        Type localVarReturnType = new TypeToken<AdminSocialProvidersCreateResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
