/*
 * LumoAuth API
 *
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using LumoAuth.ApiClient.Client;
using LumoAuth.ApiClient.Api;
// uncomment below to import models
//using LumoAuth.ApiClient.Model;

namespace LumoAuth.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing AdminSettingsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AdminSettingsApiTests : IDisposable
    {
        private AdminSettingsApi instance;

        public AdminSettingsApiTests()
        {
            instance = new AdminSettingsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdminSettingsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AdminSettingsApi
            //Assert.IsType<AdminSettingsApi>(instance);
        }

        /// <summary>
        /// Test AdminAnalyticsDashboard
        /// </summary>
        [Fact]
        public void AdminAnalyticsDashboardTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.AdminAnalyticsDashboard(orgId);
            //Assert.IsType<AdminAnalyticsDashboardResponse>(response);
        }

        /// <summary>
        /// Test AdminAnalyticsLogins
        /// </summary>
        [Fact]
        public void AdminAnalyticsLoginsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //int? days = null;
            //var response = instance.AdminAnalyticsLogins(orgId, days);
            //Assert.IsType<AdminAnalyticsLoginsResponse>(response);
        }

        /// <summary>
        /// Test AdminAnalyticsUsers
        /// </summary>
        [Fact]
        public void AdminAnalyticsUsersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //int? days = null;
            //var response = instance.AdminAnalyticsUsers(orgId, days);
            //Assert.IsType<AdminAnalyticsUsersResponse>(response);
        }

        /// <summary>
        /// Test AdminOrganizationGet
        /// </summary>
        [Fact]
        public void AdminOrganizationGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.AdminOrganizationGet(orgId);
            //Assert.IsType<AdminTenantGetResponse>(response);
        }

        /// <summary>
        /// Test AdminSettingsAll
        /// </summary>
        [Fact]
        public void AdminSettingsAllTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.AdminSettingsAll(orgId);
            //Assert.IsType<AdminSettingsAllResponse>(response);
        }

        /// <summary>
        /// Test AdminSettingsAuthGet
        /// </summary>
        [Fact]
        public void AdminSettingsAuthGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.AdminSettingsAuthGet(orgId);
            //Assert.IsType<AdminSettingsAuthenticationGetResponse>(response);
        }

        /// <summary>
        /// Test AdminSettingsAuthenticationGet
        /// </summary>
        [Fact]
        public void AdminSettingsAuthenticationGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.AdminSettingsAuthenticationGet(orgId);
            //Assert.IsType<AdminSettingsAuthenticationGetResponse>(response);
        }

        /// <summary>
        /// Test AdminSettingsBrandingGet
        /// </summary>
        [Fact]
        public void AdminSettingsBrandingGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.AdminSettingsBrandingGet(orgId);
            //Assert.IsType<AdminSettingsBrandingGetResponse>(response);
        }

        /// <summary>
        /// Test AdminSettingsEmailGet
        /// </summary>
        [Fact]
        public void AdminSettingsEmailGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.AdminSettingsEmailGet(orgId);
            //Assert.IsType<AdminSettingsEmailGetResponse>(response);
        }

        /// <summary>
        /// Test AdminSettingsGeneralGet
        /// </summary>
        [Fact]
        public void AdminSettingsGeneralGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.AdminSettingsGeneralGet(orgId);
            //Assert.IsType<AdminSettingsGeneralGetResponse>(response);
        }

        /// <summary>
        /// Test AdminSettingsScimGet
        /// </summary>
        [Fact]
        public void AdminSettingsScimGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.AdminSettingsScimGet(orgId);
            //Assert.IsType<AdminSettingsScimGetResponse>(response);
        }

        /// <summary>
        /// Test AdminSettingsSecurityGet
        /// </summary>
        [Fact]
        public void AdminSettingsSecurityGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.AdminSettingsSecurityGet(orgId);
            //Assert.IsType<AdminSettingsSecurityGetResponse>(response);
        }

        /// <summary>
        /// Test AdminTenantGet
        /// </summary>
        [Fact]
        public void AdminTenantGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.AdminTenantGet(orgId);
            //Assert.IsType<AdminTenantGetResponse>(response);
        }

        /// <summary>
        /// Test PatchAdminOrganizationUpdate
        /// </summary>
        [Fact]
        public void PatchAdminOrganizationUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.PatchAdminOrganizationUpdate(orgId);
            //Assert.IsType<PutAdminTenantUpdateResponse>(response);
        }

        /// <summary>
        /// Test PatchAdminSettingsAuthUpdate
        /// </summary>
        [Fact]
        public void PatchAdminSettingsAuthUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.PatchAdminSettingsAuthUpdate(orgId);
            //Assert.IsType<PutAdminSettingsAuthenticationUpdateResponse>(response);
        }

        /// <summary>
        /// Test PatchAdminSettingsAuthenticationUpdate
        /// </summary>
        [Fact]
        public void PatchAdminSettingsAuthenticationUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.PatchAdminSettingsAuthenticationUpdate(orgId);
            //Assert.IsType<PutAdminSettingsAuthenticationUpdateResponse>(response);
        }

        /// <summary>
        /// Test PatchAdminSettingsBrandingUpdate
        /// </summary>
        [Fact]
        public void PatchAdminSettingsBrandingUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.PatchAdminSettingsBrandingUpdate(orgId);
            //Assert.IsType<PutAdminSettingsBrandingUpdateResponse>(response);
        }

        /// <summary>
        /// Test PatchAdminSettingsEmailUpdate
        /// </summary>
        [Fact]
        public void PatchAdminSettingsEmailUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.PatchAdminSettingsEmailUpdate(orgId);
            //Assert.IsType<PutAdminSettingsEmailUpdateResponse>(response);
        }

        /// <summary>
        /// Test PatchAdminSettingsGeneralUpdate
        /// </summary>
        [Fact]
        public void PatchAdminSettingsGeneralUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.PatchAdminSettingsGeneralUpdate(orgId);
            //Assert.IsType<PutAdminSettingsGeneralUpdateResponse>(response);
        }

        /// <summary>
        /// Test PatchAdminSettingsScimUpdate
        /// </summary>
        [Fact]
        public void PatchAdminSettingsScimUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.PatchAdminSettingsScimUpdate(orgId);
            //Assert.IsType<PutAdminSettingsScimUpdateResponse>(response);
        }

        /// <summary>
        /// Test PatchAdminSettingsSecurityUpdate
        /// </summary>
        [Fact]
        public void PatchAdminSettingsSecurityUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.PatchAdminSettingsSecurityUpdate(orgId);
            //Assert.IsType<PutAdminSettingsSecurityUpdateResponse>(response);
        }

        /// <summary>
        /// Test PatchAdminTenantUpdate
        /// </summary>
        [Fact]
        public void PatchAdminTenantUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.PatchAdminTenantUpdate(orgId);
            //Assert.IsType<PutAdminTenantUpdateResponse>(response);
        }

        /// <summary>
        /// Test PutAdminOrganizationUpdate
        /// </summary>
        [Fact]
        public void PutAdminOrganizationUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.PutAdminOrganizationUpdate(orgId);
            //Assert.IsType<PutAdminTenantUpdateResponse>(response);
        }

        /// <summary>
        /// Test PutAdminSettingsAuthUpdate
        /// </summary>
        [Fact]
        public void PutAdminSettingsAuthUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.PutAdminSettingsAuthUpdate(orgId);
            //Assert.IsType<PutAdminSettingsAuthenticationUpdateResponse>(response);
        }

        /// <summary>
        /// Test PutAdminSettingsAuthenticationUpdate
        /// </summary>
        [Fact]
        public void PutAdminSettingsAuthenticationUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.PutAdminSettingsAuthenticationUpdate(orgId);
            //Assert.IsType<PutAdminSettingsAuthenticationUpdateResponse>(response);
        }

        /// <summary>
        /// Test PutAdminSettingsBrandingUpdate
        /// </summary>
        [Fact]
        public void PutAdminSettingsBrandingUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.PutAdminSettingsBrandingUpdate(orgId);
            //Assert.IsType<PutAdminSettingsBrandingUpdateResponse>(response);
        }

        /// <summary>
        /// Test PutAdminSettingsEmailUpdate
        /// </summary>
        [Fact]
        public void PutAdminSettingsEmailUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.PutAdminSettingsEmailUpdate(orgId);
            //Assert.IsType<PutAdminSettingsEmailUpdateResponse>(response);
        }

        /// <summary>
        /// Test PutAdminSettingsGeneralUpdate
        /// </summary>
        [Fact]
        public void PutAdminSettingsGeneralUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.PutAdminSettingsGeneralUpdate(orgId);
            //Assert.IsType<PutAdminSettingsGeneralUpdateResponse>(response);
        }

        /// <summary>
        /// Test PutAdminSettingsScimUpdate
        /// </summary>
        [Fact]
        public void PutAdminSettingsScimUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.PutAdminSettingsScimUpdate(orgId);
            //Assert.IsType<PutAdminSettingsScimUpdateResponse>(response);
        }

        /// <summary>
        /// Test PutAdminSettingsSecurityUpdate
        /// </summary>
        [Fact]
        public void PutAdminSettingsSecurityUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.PutAdminSettingsSecurityUpdate(orgId);
            //Assert.IsType<PutAdminSettingsSecurityUpdateResponse>(response);
        }

        /// <summary>
        /// Test PutAdminTenantUpdate
        /// </summary>
        [Fact]
        public void PutAdminTenantUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orgId = null;
            //var response = instance.PutAdminTenantUpdate(orgId);
            //Assert.IsType<PutAdminTenantUpdateResponse>(response);
        }
    }
}
