/*
 * LumoAuth API
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lumoauth.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EvaluateResponseContextReasonAdmin
 */
public class EvaluateResponseContextReasonAdminTest {
    private final EvaluateResponseContextReasonAdmin model = new EvaluateResponseContextReasonAdmin();

    /**
     * Model tests for EvaluateResponseContextReasonAdmin
     */
    @Test
    public void testEvaluateResponseContextReasonAdmin() {
        // TODO: test EvaluateResponseContextReasonAdmin
    }

    /**
     * Test the property 'en'
     */
    @Test
    public void enTest() {
        // TODO: test en
    }

}
