/*
 * LumoAuth API
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lumoauth.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetAgentCardResponseSignaturesItem
 */
public class GetAgentCardResponseSignaturesItemTest {
    private final GetAgentCardResponseSignaturesItem model = new GetAgentCardResponseSignaturesItem();

    /**
     * Model tests for GetAgentCardResponseSignaturesItem
     */
    @Test
    public void testGetAgentCardResponseSignaturesItem() {
        // TODO: test GetAgentCardResponseSignaturesItem
    }

    /**
     * Test the property '_protected'
     */
    @Test
    public void _protectedTest() {
        // TODO: test _protected
    }

    /**
     * Test the property 'signature'
     */
    @Test
    public void signatureTest() {
        // TODO: test signature
    }

}
