/*
 * LumoAuth API
 *
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LumoAuth.ApiClient.Model;
using LumoAuth.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LumoAuth.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AdminGroupsGetMembersResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdminGroupsGetMembersResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdminGroupsGetMembersResponse
        //private AdminGroupsGetMembersResponse instance;

        public AdminGroupsGetMembersResponseTests()
        {
            // TODO uncomment below to create an instance of AdminGroupsGetMembersResponse
            //instance = new AdminGroupsGetMembersResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdminGroupsGetMembersResponse
        /// </summary>
        [Fact]
        public void AdminGroupsGetMembersResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdminGroupsGetMembersResponse
            //Assert.IsType<AdminGroupsGetMembersResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }

        /// <summary>
        /// Test the property 'Pagination'
        /// </summary>
        [Fact]
        public void PaginationTest()
        {
            // TODO unit test for the property 'Pagination'
        }

        /// <summary>
        /// Test the property 'ResourceType'
        /// </summary>
        [Fact]
        public void ResourceTypeTest()
        {
            // TODO unit test for the property 'ResourceType'
        }
    }
}
