/*
 * LumoAuth API
 *
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LumoAuth.ApiClient.Model;
using LumoAuth.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LumoAuth.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AdminTokensRevokeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdminTokensRevokeResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdminTokensRevokeResponse
        //private AdminTokensRevokeResponse instance;

        public AdminTokensRevokeResponseTests()
        {
            // TODO uncomment below to create an instance of AdminTokensRevokeResponse
            //instance = new AdminTokensRevokeResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdminTokensRevokeResponse
        /// </summary>
        [Fact]
        public void AdminTokensRevokeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdminTokensRevokeResponse
            //Assert.IsType<AdminTokensRevokeResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
