/*
 * LumoAuth API
 *
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LumoAuth.ApiClient.Model;
using LumoAuth.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LumoAuth.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing GenerateRecoveryCodesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenerateRecoveryCodesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GenerateRecoveryCodesResponse
        //private GenerateRecoveryCodesResponse instance;

        public GenerateRecoveryCodesResponseTests()
        {
            // TODO uncomment below to create an instance of GenerateRecoveryCodesResponse
            //instance = new GenerateRecoveryCodesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GenerateRecoveryCodesResponse
        /// </summary>
        [Fact]
        public void GenerateRecoveryCodesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GenerateRecoveryCodesResponse
            //Assert.IsType<GenerateRecoveryCodesResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Codes'
        /// </summary>
        [Fact]
        public void CodesTest()
        {
            // TODO unit test for the property 'Codes'
        }

        /// <summary>
        /// Test the property 'Remaining'
        /// </summary>
        [Fact]
        public void RemainingTest()
        {
            // TODO unit test for the property 'Remaining'
        }

        /// <summary>
        /// Test the property 'GeneratedAt'
        /// </summary>
        [Fact]
        public void GeneratedAtTest()
        {
            // TODO unit test for the property 'GeneratedAt'
        }
    }
}
