/*
 * LumoAuth API
 *
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LumoAuth.ApiClient.Model;
using LumoAuth.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LumoAuth.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing MfaAuthenticator
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MfaAuthenticatorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MfaAuthenticator
        //private MfaAuthenticator instance;

        public MfaAuthenticatorTests()
        {
            // TODO uncomment below to create an instance of MfaAuthenticator
            //instance = new MfaAuthenticator();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MfaAuthenticator
        /// </summary>
        [Fact]
        public void MfaAuthenticatorInstanceTest()
        {
            // TODO uncomment below to test "IsType" MfaAuthenticator
            //Assert.IsType<MfaAuthenticator>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'IsDefault'
        /// </summary>
        [Fact]
        public void IsDefaultTest()
        {
            // TODO unit test for the property 'IsDefault'
        }

        /// <summary>
        /// Test the property 'Tier'
        /// </summary>
        [Fact]
        public void TierTest()
        {
            // TODO unit test for the property 'Tier'
        }

        /// <summary>
        /// Test the property 'TierLabel'
        /// </summary>
        [Fact]
        public void TierLabelTest()
        {
            // TODO unit test for the property 'TierLabel'
        }

        /// <summary>
        /// Test the property 'Amr'
        /// </summary>
        [Fact]
        public void AmrTest()
        {
            // TODO unit test for the property 'Amr'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'ActivatedAt'
        /// </summary>
        [Fact]
        public void ActivatedAtTest()
        {
            // TODO unit test for the property 'ActivatedAt'
        }

        /// <summary>
        /// Test the property 'LastUsedAt'
        /// </summary>
        [Fact]
        public void LastUsedAtTest()
        {
            // TODO unit test for the property 'LastUsedAt'
        }

        /// <summary>
        /// Test the property 'LastUsedContext'
        /// </summary>
        [Fact]
        public void LastUsedContextTest()
        {
            // TODO unit test for the property 'LastUsedContext'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
    }
}
