/*
 * LumoAuth API
 *
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LumoAuth.ApiClient.Model;
using LumoAuth.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LumoAuth.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing RequestPermissionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestPermissionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestPermissionRequest
        //private RequestPermissionRequest instance;

        public RequestPermissionRequestTests()
        {
            // TODO uncomment below to create an instance of RequestPermissionRequest
            //instance = new RequestPermissionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestPermissionRequest
        /// </summary>
        [Fact]
        public void RequestPermissionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RequestPermissionRequest
            //Assert.IsType<RequestPermissionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TaskId'
        /// </summary>
        [Fact]
        public void TaskIdTest()
        {
            // TODO unit test for the property 'TaskId'
        }

        /// <summary>
        /// Test the property 'AuthorizationDetails'
        /// </summary>
        [Fact]
        public void AuthorizationDetailsTest()
        {
            // TODO unit test for the property 'AuthorizationDetails'
        }

        /// <summary>
        /// Test the property 'Justification'
        /// </summary>
        [Fact]
        public void JustificationTest()
        {
            // TODO unit test for the property 'Justification'
        }

        /// <summary>
        /// Test the property 'RequestedTtl'
        /// </summary>
        [Fact]
        public void RequestedTtlTest()
        {
            // TODO unit test for the property 'RequestedTtl'
        }

        /// <summary>
        /// Test the property 'CallbackUrl'
        /// </summary>
        [Fact]
        public void CallbackUrlTest()
        {
            // TODO unit test for the property 'CallbackUrl'
        }
    }
}
