/*
 * LumoAuth API
 *
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LumoAuth.ApiClient.Model;
using LumoAuth.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LumoAuth.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing SignedAgentCard
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SignedAgentCardTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SignedAgentCard
        //private SignedAgentCard instance;

        public SignedAgentCardTests()
        {
            // TODO uncomment below to create an instance of SignedAgentCard
            //instance = new SignedAgentCard();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SignedAgentCard
        /// </summary>
        [Fact]
        public void SignedAgentCardInstanceTest()
        {
            // TODO uncomment below to test "IsType" SignedAgentCard
            //Assert.IsType<SignedAgentCard>(instance);
        }

        /// <summary>
        /// Test the property 'ProtocolVersion'
        /// </summary>
        [Fact]
        public void ProtocolVersionTest()
        {
            // TODO unit test for the property 'ProtocolVersion'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'PreferredTransport'
        /// </summary>
        [Fact]
        public void PreferredTransportTest()
        {
            // TODO unit test for the property 'PreferredTransport'
        }

        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Fact]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }

        /// <summary>
        /// Test the property 'Capabilities'
        /// </summary>
        [Fact]
        public void CapabilitiesTest()
        {
            // TODO unit test for the property 'Capabilities'
        }

        /// <summary>
        /// Test the property 'DefaultInputModes'
        /// </summary>
        [Fact]
        public void DefaultInputModesTest()
        {
            // TODO unit test for the property 'DefaultInputModes'
        }

        /// <summary>
        /// Test the property 'DefaultOutputModes'
        /// </summary>
        [Fact]
        public void DefaultOutputModesTest()
        {
            // TODO unit test for the property 'DefaultOutputModes'
        }

        /// <summary>
        /// Test the property 'SecuritySchemes'
        /// </summary>
        [Fact]
        public void SecuritySchemesTest()
        {
            // TODO unit test for the property 'SecuritySchemes'
        }

        /// <summary>
        /// Test the property 'Security'
        /// </summary>
        [Fact]
        public void SecurityTest()
        {
            // TODO unit test for the property 'Security'
        }

        /// <summary>
        /// Test the property 'Skills'
        /// </summary>
        [Fact]
        public void SkillsTest()
        {
            // TODO unit test for the property 'Skills'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'Signatures'
        /// </summary>
        [Fact]
        public void SignaturesTest()
        {
            // TODO unit test for the property 'Signatures'
        }
    }
}
