=begin
#LumoAuth API

#LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 

The version of the OpenAPI document: 1.0.0
Contact: sdk@lumoauth.dev
Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

# Common files
require 'lumoauth_api_client/api_client'
require 'lumoauth_api_client/api_error'
require 'lumoauth_api_client/version'
require 'lumoauth_api_client/configuration'

# Models
require 'lumoauth_api_client/models/admin_agents_activate_response'
require 'lumoauth_api_client/models/admin_agents_agents_disable_response'
require 'lumoauth_api_client/models/admin_agents_agents_enable_response'
require 'lumoauth_api_client/models/admin_agents_agents_rotate_key_response'
require 'lumoauth_api_client/models/admin_agents_create_request'
require 'lumoauth_api_client/models/admin_agents_create_response'
require 'lumoauth_api_client/models/admin_agents_deactivate_response'
require 'lumoauth_api_client/models/admin_agents_generate_token_request'
require 'lumoauth_api_client/models/admin_agents_generate_token_response'
require 'lumoauth_api_client/models/admin_agents_get_response'
require 'lumoauth_api_client/models/admin_agents_get_scopes_response'
require 'lumoauth_api_client/models/admin_agents_list_response'
require 'lumoauth_api_client/models/admin_agents_revoke_key_response'
require 'lumoauth_api_client/models/admin_agents_rotate_credentials_response'
require 'lumoauth_api_client/models/admin_agents_set_scopes_request'
require 'lumoauth_api_client/models/admin_agents_set_scopes_response'
require 'lumoauth_api_client/models/approve_request_request'
require 'lumoauth_api_client/models/approve_request_response'
require 'lumoauth_api_client/models/ask_request'
require 'lumoauth_api_client/models/ask_response'
require 'lumoauth_api_client/models/authorize_mcp_request'
require 'lumoauth_api_client/models/authorize_mcp_response'
require 'lumoauth_api_client/models/complete_task_response'
require 'lumoauth_api_client/models/create_approval_request'
require 'lumoauth_api_client/models/create_approval_response'
require 'lumoauth_api_client/models/create_approval_response202'
require 'lumoauth_api_client/models/create_task_request'
require 'lumoauth_api_client/models/create_task_response'
require 'lumoauth_api_client/models/deny_request_request'
require 'lumoauth_api_client/models/deny_request_response'
require 'lumoauth_api_client/models/expand_relation_request'
require 'lumoauth_api_client/models/expand_relation_response'
require 'lumoauth_api_client/models/expand_relation_response_tree'
require 'lumoauth_api_client/models/get_approval_status_response'
require 'lumoauth_api_client/models/get_approval_status_response_approved_by'
require 'lumoauth_api_client/models/get_current_agent_response'
require 'lumoauth_api_client/models/get_current_agent_response_identity'
require 'lumoauth_api_client/models/get_current_agent_response_workspace'
require 'lumoauth_api_client/models/get_issuer_metadata_response'
require 'lumoauth_api_client/models/get_me_response'
require 'lumoauth_api_client/models/get_me_response_tenant'
require 'lumoauth_api_client/models/get_request_status_response'
require 'lumoauth_api_client/models/get_request_token_response'
require 'lumoauth_api_client/models/get_server_response'
require 'lumoauth_api_client/models/get_server_response_discovery'
require 'lumoauth_api_client/models/issue_agent_token_request'
require 'lumoauth_api_client/models/issue_agent_token_response'
require 'lumoauth_api_client/models/issue_delegate_token_request'
require 'lumoauth_api_client/models/issue_delegate_token_response'
require 'lumoauth_api_client/models/issue_platform_token_request'
require 'lumoauth_api_client/models/issue_platform_token_response'
require 'lumoauth_api_client/models/issue_resource_token_request'
require 'lumoauth_api_client/models/issue_resource_token_response'
require 'lumoauth_api_client/models/jwks_response'
require 'lumoauth_api_client/models/list_pending_requests_response'
require 'lumoauth_api_client/models/list_servers_response'
require 'lumoauth_api_client/models/list_servers_response_data_item'
require 'lumoauth_api_client/models/message_response'
require 'lumoauth_api_client/models/put_admin_agents_update_request'
require 'lumoauth_api_client/models/put_admin_agents_update_response'
require 'lumoauth_api_client/models/request_permission_request'
require 'lumoauth_api_client/models/request_permission_response'
require 'lumoauth_api_client/models/revoke_agent_token_request'
require 'lumoauth_api_client/models/revoke_agent_token_response'
require 'lumoauth_api_client/models/verify_auth_token_request'
require 'lumoauth_api_client/models/verify_auth_token_response'
require 'lumoauth_api_client/models/verify_resource_token_request'
require 'lumoauth_api_client/models/verify_resource_token_response'

# APIs
require 'lumoauth_api_client/api/a_auth_api'
require 'lumoauth_api_client/api/admin_abac_api'
require 'lumoauth_api_client/api/admin_agents_api'
require 'lumoauth_api_client/api/admin_audit_logs_api'
require 'lumoauth_api_client/api/admin_email_api'
require 'lumoauth_api_client/api/admin_groups_api'
require 'lumoauth_api_client/api/admin_identity_providers_api'
require 'lumoauth_api_client/api/admin_mcp_api'
require 'lumoauth_api_client/api/admin_o_auth_clients_api'
require 'lumoauth_api_client/api/admin_organizations_api'
require 'lumoauth_api_client/api/admin_permissions_api'
require 'lumoauth_api_client/api/admin_roles_api'
require 'lumoauth_api_client/api/admin_sandbox_api'
require 'lumoauth_api_client/api/admin_sessions_api'
require 'lumoauth_api_client/api/admin_settings_api'
require 'lumoauth_api_client/api/admin_users_api'
require 'lumoauth_api_client/api/admin_webhooks_api'
require 'lumoauth_api_client/api/agents_api'
require 'lumoauth_api_client/api/authorization_api'
require 'lumoauth_api_client/api/identity_api'
require 'lumoauth_api_client/api/jit_api'
require 'lumoauth_api_client/api/mcp_api'
require 'lumoauth_api_client/api/o_auth_api'
require 'lumoauth_api_client/api/oidc_api'
require 'lumoauth_api_client/api/ssf_api'
require 'lumoauth_api_client/api/token_vault_api'
require 'lumoauth_api_client/api/well_known_api'

module LumoAuthApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   LumoAuthApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
