/*
LumoAuth API

Testing AdminPermissionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package lumoauthclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/lumoauth/api-clients/go"
)

func Test_lumoauthclient_AdminPermissionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AdminPermissionsAPIService AdminPermissionsCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string

		httpRes, err := apiClient.AdminPermissionsAPI.AdminPermissionsCreate(context.Background(), orgId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdminPermissionsAPIService AdminPermissionsDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var permissionId string

		httpRes, err := apiClient.AdminPermissionsAPI.AdminPermissionsDelete(context.Background(), orgId, permissionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdminPermissionsAPIService AdminPermissionsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var permissionId string

		httpRes, err := apiClient.AdminPermissionsAPI.AdminPermissionsGet(context.Background(), orgId, permissionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdminPermissionsAPIService AdminPermissionsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string

		httpRes, err := apiClient.AdminPermissionsAPI.AdminPermissionsList(context.Background(), orgId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdminPermissionsAPIService AdminPermissionsUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var permissionId string

		httpRes, err := apiClient.AdminPermissionsAPI.AdminPermissionsUpdate(context.Background(), orgId, permissionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdminPermissionsAPIService AdminPermissionsUsage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var permissionId string

		httpRes, err := apiClient.AdminPermissionsAPI.AdminPermissionsUsage(context.Background(), orgId, permissionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdminPermissionsAPIService AdminScopesCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string

		httpRes, err := apiClient.AdminPermissionsAPI.AdminScopesCreate(context.Background(), orgId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdminPermissionsAPIService AdminScopesDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var scopeId string

		httpRes, err := apiClient.AdminPermissionsAPI.AdminScopesDelete(context.Background(), orgId, scopeId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdminPermissionsAPIService AdminScopesList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string

		httpRes, err := apiClient.AdminPermissionsAPI.AdminScopesList(context.Background(), orgId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
