/*
 * LumoAuth API
 *
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = LumoAuth.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = LumoAuth.ApiClient.Client.OpenAPIDateConverter;

namespace LumoAuth.ApiClient.Model
{
    /// <summary>
    /// AdminWebhooksDeliveriesListResponseMeta
    /// </summary>
    [DataContract(Name = "AdminWebhooksDeliveriesListResponseMeta")]
    public partial class AdminWebhooksDeliveriesListResponseMeta : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdminWebhooksDeliveriesListResponseMeta" /> class.
        /// </summary>
        /// <param name="count">Number of rows returned.</param>
        /// <param name="deadLetteredCount">Dead-lettered deliveries for this webhook (unfiltered).</param>
        public AdminWebhooksDeliveriesListResponseMeta(int count = default, int deadLetteredCount = default)
        {
            this.Count = count;
            this.DeadLetteredCount = deadLetteredCount;
        }

        /// <summary>
        /// Number of rows returned
        /// </summary>
        /// <value>Number of rows returned</value>
        [DataMember(Name = "count", EmitDefaultValue = false)]
        public int Count { get; set; }

        /// <summary>
        /// Dead-lettered deliveries for this webhook (unfiltered)
        /// </summary>
        /// <value>Dead-lettered deliveries for this webhook (unfiltered)</value>
        [DataMember(Name = "dead_lettered_count", EmitDefaultValue = false)]
        public int DeadLetteredCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AdminWebhooksDeliveriesListResponseMeta {\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  DeadLetteredCount: ").Append(DeadLetteredCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
