/*
 * LumoAuth API
 *
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = LumoAuth.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = LumoAuth.ApiClient.Client.OpenAPIDateConverter;

namespace LumoAuth.ApiClient.Model
{
    /// <summary>
    /// IssueTemporaryAccessCodeRequest
    /// </summary>
    [DataContract(Name = "IssueTemporaryAccessCodeRequest")]
    public partial class IssueTemporaryAccessCodeRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IssueTemporaryAccessCodeRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected IssueTemporaryAccessCodeRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="IssueTemporaryAccessCodeRequest" /> class.
        /// </summary>
        /// <param name="reason">reason (required).</param>
        /// <param name="ttlMinutes">ttlMinutes (default to 60).</param>
        /// <param name="singleUse">singleUse (default to true).</param>
        public IssueTemporaryAccessCodeRequest(string reason = default, int ttlMinutes = 60, bool singleUse = true)
        {
            // to ensure "reason" is required (not null)
            if (reason == null)
            {
                throw new ArgumentNullException("reason is a required property for IssueTemporaryAccessCodeRequest and cannot be null");
            }
            this.Reason = reason;
            this.TtlMinutes = ttlMinutes;
            this.SingleUse = singleUse;
        }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        /*
        <example>User lost phone; identity verified by video call</example>
        */
        [DataMember(Name = "reason", IsRequired = true, EmitDefaultValue = true)]
        public string Reason { get; set; }

        /// <summary>
        /// Gets or Sets TtlMinutes
        /// </summary>
        [DataMember(Name = "ttl_minutes", EmitDefaultValue = false)]
        public int TtlMinutes { get; set; }

        /// <summary>
        /// Gets or Sets SingleUse
        /// </summary>
        [DataMember(Name = "single_use", EmitDefaultValue = true)]
        public bool SingleUse { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IssueTemporaryAccessCodeRequest {\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  TtlMinutes: ").Append(TtlMinutes).Append("\n");
            sb.Append("  SingleUse: ").Append(SingleUse).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TtlMinutes (int) maximum
            if (this.TtlMinutes > (int)10080)
            {
                yield return new ValidationResult("Invalid value for TtlMinutes, must be a value less than or equal to 10080.", new [] { "TtlMinutes" });
            }

            // TtlMinutes (int) minimum
            if (this.TtlMinutes < (int)5)
            {
                yield return new ValidationResult("Invalid value for TtlMinutes, must be a value greater than or equal to 5.", new [] { "TtlMinutes" });
            }

            yield break;
        }
    }

}
