/*
 * LumoAuth API
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lumoauth.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.lumoauth.client.JSON;

/**
 * AdminAnalyticsLoginsResponseDataDailyItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-10-08T10:39:00.868661198-07:00[America/Los_Angeles]", comments = "Generator version: 7.14.0")
public class AdminAnalyticsLoginsResponseDataDailyItem {
  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  @javax.annotation.Nullable
  private LocalDate date;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  @javax.annotation.Nullable
  private Integer total;

  public static final String SERIALIZED_NAME_SUCCESSFUL = "successful";
  @SerializedName(SERIALIZED_NAME_SUCCESSFUL)
  @javax.annotation.Nullable
  private Integer successful;

  public static final String SERIALIZED_NAME_FAILED = "failed";
  @SerializedName(SERIALIZED_NAME_FAILED)
  @javax.annotation.Nullable
  private Integer failed;

  public AdminAnalyticsLoginsResponseDataDailyItem() {
  }

  public AdminAnalyticsLoginsResponseDataDailyItem date(@javax.annotation.Nullable LocalDate date) {
    this.date = date;
    return this;
  }

  /**
   * Get date
   * @return date
   */
  @javax.annotation.Nullable
  public LocalDate getDate() {
    return date;
  }

  public void setDate(@javax.annotation.Nullable LocalDate date) {
    this.date = date;
  }


  public AdminAnalyticsLoginsResponseDataDailyItem total(@javax.annotation.Nullable Integer total) {
    this.total = total;
    return this;
  }

  /**
   * Get total
   * @return total
   */
  @javax.annotation.Nullable
  public Integer getTotal() {
    return total;
  }

  public void setTotal(@javax.annotation.Nullable Integer total) {
    this.total = total;
  }


  public AdminAnalyticsLoginsResponseDataDailyItem successful(@javax.annotation.Nullable Integer successful) {
    this.successful = successful;
    return this;
  }

  /**
   * Get successful
   * @return successful
   */
  @javax.annotation.Nullable
  public Integer getSuccessful() {
    return successful;
  }

  public void setSuccessful(@javax.annotation.Nullable Integer successful) {
    this.successful = successful;
  }


  public AdminAnalyticsLoginsResponseDataDailyItem failed(@javax.annotation.Nullable Integer failed) {
    this.failed = failed;
    return this;
  }

  /**
   * Get failed
   * @return failed
   */
  @javax.annotation.Nullable
  public Integer getFailed() {
    return failed;
  }

  public void setFailed(@javax.annotation.Nullable Integer failed) {
    this.failed = failed;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminAnalyticsLoginsResponseDataDailyItem adminAnalyticsLoginsResponseDataDailyItem = (AdminAnalyticsLoginsResponseDataDailyItem) o;
    return Objects.equals(this.date, adminAnalyticsLoginsResponseDataDailyItem.date) &&
        Objects.equals(this.total, adminAnalyticsLoginsResponseDataDailyItem.total) &&
        Objects.equals(this.successful, adminAnalyticsLoginsResponseDataDailyItem.successful) &&
        Objects.equals(this.failed, adminAnalyticsLoginsResponseDataDailyItem.failed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, total, successful, failed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminAnalyticsLoginsResponseDataDailyItem {\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    successful: ").append(toIndentedString(successful)).append("\n");
    sb.append("    failed: ").append(toIndentedString(failed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("date", "total", "successful", "failed"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AdminAnalyticsLoginsResponseDataDailyItem
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AdminAnalyticsLoginsResponseDataDailyItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AdminAnalyticsLoginsResponseDataDailyItem is not found in the empty JSON string", AdminAnalyticsLoginsResponseDataDailyItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AdminAnalyticsLoginsResponseDataDailyItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AdminAnalyticsLoginsResponseDataDailyItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AdminAnalyticsLoginsResponseDataDailyItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AdminAnalyticsLoginsResponseDataDailyItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AdminAnalyticsLoginsResponseDataDailyItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AdminAnalyticsLoginsResponseDataDailyItem.class));

       return (TypeAdapter<T>) new TypeAdapter<AdminAnalyticsLoginsResponseDataDailyItem>() {
           @Override
           public void write(JsonWriter out, AdminAnalyticsLoginsResponseDataDailyItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AdminAnalyticsLoginsResponseDataDailyItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AdminAnalyticsLoginsResponseDataDailyItem given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AdminAnalyticsLoginsResponseDataDailyItem
   * @throws IOException if the JSON string is invalid with respect to AdminAnalyticsLoginsResponseDataDailyItem
   */
  public static AdminAnalyticsLoginsResponseDataDailyItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AdminAnalyticsLoginsResponseDataDailyItem.class);
  }

  /**
   * Convert an instance of AdminAnalyticsLoginsResponseDataDailyItem to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

