/*
 * LumoAuth API
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lumoauth.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.lumoauth.client.JSON;

/**
 * GetJwksResponseKeysItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-10-08T10:39:00.868661198-07:00[America/Los_Angeles]", comments = "Generator version: 7.14.0")
public class GetJwksResponseKeysItem {
  /**
   * Gets or Sets kty
   */
  @JsonAdapter(KtyEnum.Adapter.class)
  public enum KtyEnum {
    RSA("RSA"),
    
    EC("EC");

    private String value;

    KtyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static KtyEnum fromValue(String value) {
      for (KtyEnum b : KtyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<KtyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final KtyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public KtyEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return KtyEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      KtyEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_KTY = "kty";
  @SerializedName(SERIALIZED_NAME_KTY)
  @javax.annotation.Nonnull
  private KtyEnum kty;

  public static final String SERIALIZED_NAME_KID = "kid";
  @SerializedName(SERIALIZED_NAME_KID)
  @javax.annotation.Nonnull
  private String kid;

  public static final String SERIALIZED_NAME_USE = "use";
  @SerializedName(SERIALIZED_NAME_USE)
  @javax.annotation.Nullable
  private String use;

  public static final String SERIALIZED_NAME_ALG = "alg";
  @SerializedName(SERIALIZED_NAME_ALG)
  @javax.annotation.Nullable
  private String alg;

  public static final String SERIALIZED_NAME_N = "n";
  @SerializedName(SERIALIZED_NAME_N)
  @javax.annotation.Nullable
  private String n;

  public static final String SERIALIZED_NAME_E = "e";
  @SerializedName(SERIALIZED_NAME_E)
  @javax.annotation.Nullable
  private String e;

  public static final String SERIALIZED_NAME_CRV = "crv";
  @SerializedName(SERIALIZED_NAME_CRV)
  @javax.annotation.Nullable
  private String crv;

  public static final String SERIALIZED_NAME_X = "x";
  @SerializedName(SERIALIZED_NAME_X)
  @javax.annotation.Nullable
  private String x;

  public static final String SERIALIZED_NAME_Y = "y";
  @SerializedName(SERIALIZED_NAME_Y)
  @javax.annotation.Nullable
  private String y;

  public GetJwksResponseKeysItem() {
  }

  public GetJwksResponseKeysItem kty(@javax.annotation.Nonnull KtyEnum kty) {
    this.kty = kty;
    return this;
  }

  /**
   * Get kty
   * @return kty
   */
  @javax.annotation.Nonnull
  public KtyEnum getKty() {
    return kty;
  }

  public void setKty(@javax.annotation.Nonnull KtyEnum kty) {
    this.kty = kty;
  }


  public GetJwksResponseKeysItem kid(@javax.annotation.Nonnull String kid) {
    this.kid = kid;
    return this;
  }

  /**
   * Get kid
   * @return kid
   */
  @javax.annotation.Nonnull
  public String getKid() {
    return kid;
  }

  public void setKid(@javax.annotation.Nonnull String kid) {
    this.kid = kid;
  }


  public GetJwksResponseKeysItem use(@javax.annotation.Nullable String use) {
    this.use = use;
    return this;
  }

  /**
   * Get use
   * @return use
   */
  @javax.annotation.Nullable
  public String getUse() {
    return use;
  }

  public void setUse(@javax.annotation.Nullable String use) {
    this.use = use;
  }


  public GetJwksResponseKeysItem alg(@javax.annotation.Nullable String alg) {
    this.alg = alg;
    return this;
  }

  /**
   * Get alg
   * @return alg
   */
  @javax.annotation.Nullable
  public String getAlg() {
    return alg;
  }

  public void setAlg(@javax.annotation.Nullable String alg) {
    this.alg = alg;
  }


  public GetJwksResponseKeysItem n(@javax.annotation.Nullable String n) {
    this.n = n;
    return this;
  }

  /**
   * RSA modulus, base64url (RSA keys).
   * @return n
   */
  @javax.annotation.Nullable
  public String getN() {
    return n;
  }

  public void setN(@javax.annotation.Nullable String n) {
    this.n = n;
  }


  public GetJwksResponseKeysItem e(@javax.annotation.Nullable String e) {
    this.e = e;
    return this;
  }

  /**
   * RSA exponent, base64url (RSA keys).
   * @return e
   */
  @javax.annotation.Nullable
  public String getE() {
    return e;
  }

  public void setE(@javax.annotation.Nullable String e) {
    this.e = e;
  }


  public GetJwksResponseKeysItem crv(@javax.annotation.Nullable String crv) {
    this.crv = crv;
    return this;
  }

  /**
   * Curve name (EC keys).
   * @return crv
   */
  @javax.annotation.Nullable
  public String getCrv() {
    return crv;
  }

  public void setCrv(@javax.annotation.Nullable String crv) {
    this.crv = crv;
  }


  public GetJwksResponseKeysItem x(@javax.annotation.Nullable String x) {
    this.x = x;
    return this;
  }

  /**
   * EC x coordinate, base64url (EC keys).
   * @return x
   */
  @javax.annotation.Nullable
  public String getX() {
    return x;
  }

  public void setX(@javax.annotation.Nullable String x) {
    this.x = x;
  }


  public GetJwksResponseKeysItem y(@javax.annotation.Nullable String y) {
    this.y = y;
    return this;
  }

  /**
   * EC y coordinate, base64url (EC keys).
   * @return y
   */
  @javax.annotation.Nullable
  public String getY() {
    return y;
  }

  public void setY(@javax.annotation.Nullable String y) {
    this.y = y;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetJwksResponseKeysItem getJwksResponseKeysItem = (GetJwksResponseKeysItem) o;
    return Objects.equals(this.kty, getJwksResponseKeysItem.kty) &&
        Objects.equals(this.kid, getJwksResponseKeysItem.kid) &&
        Objects.equals(this.use, getJwksResponseKeysItem.use) &&
        Objects.equals(this.alg, getJwksResponseKeysItem.alg) &&
        Objects.equals(this.n, getJwksResponseKeysItem.n) &&
        Objects.equals(this.e, getJwksResponseKeysItem.e) &&
        Objects.equals(this.crv, getJwksResponseKeysItem.crv) &&
        Objects.equals(this.x, getJwksResponseKeysItem.x) &&
        Objects.equals(this.y, getJwksResponseKeysItem.y);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kty, kid, use, alg, n, e, crv, x, y);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetJwksResponseKeysItem {\n");
    sb.append("    kty: ").append(toIndentedString(kty)).append("\n");
    sb.append("    kid: ").append(toIndentedString(kid)).append("\n");
    sb.append("    use: ").append(toIndentedString(use)).append("\n");
    sb.append("    alg: ").append(toIndentedString(alg)).append("\n");
    sb.append("    n: ").append(toIndentedString(n)).append("\n");
    sb.append("    e: ").append(toIndentedString(e)).append("\n");
    sb.append("    crv: ").append(toIndentedString(crv)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("kty", "kid", "use", "alg", "n", "e", "crv", "x", "y"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("kty", "kid"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetJwksResponseKeysItem
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetJwksResponseKeysItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetJwksResponseKeysItem is not found in the empty JSON string", GetJwksResponseKeysItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetJwksResponseKeysItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetJwksResponseKeysItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetJwksResponseKeysItem.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("kty").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `kty` to be a primitive type in the JSON string but got `%s`", jsonObj.get("kty").toString()));
      }
      // validate the required field `kty`
      KtyEnum.validateJsonElement(jsonObj.get("kty"));
      if (!jsonObj.get("kid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `kid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("kid").toString()));
      }
      if ((jsonObj.get("use") != null && !jsonObj.get("use").isJsonNull()) && !jsonObj.get("use").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `use` to be a primitive type in the JSON string but got `%s`", jsonObj.get("use").toString()));
      }
      if ((jsonObj.get("alg") != null && !jsonObj.get("alg").isJsonNull()) && !jsonObj.get("alg").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `alg` to be a primitive type in the JSON string but got `%s`", jsonObj.get("alg").toString()));
      }
      if ((jsonObj.get("n") != null && !jsonObj.get("n").isJsonNull()) && !jsonObj.get("n").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `n` to be a primitive type in the JSON string but got `%s`", jsonObj.get("n").toString()));
      }
      if ((jsonObj.get("e") != null && !jsonObj.get("e").isJsonNull()) && !jsonObj.get("e").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `e` to be a primitive type in the JSON string but got `%s`", jsonObj.get("e").toString()));
      }
      if ((jsonObj.get("crv") != null && !jsonObj.get("crv").isJsonNull()) && !jsonObj.get("crv").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `crv` to be a primitive type in the JSON string but got `%s`", jsonObj.get("crv").toString()));
      }
      if ((jsonObj.get("x") != null && !jsonObj.get("x").isJsonNull()) && !jsonObj.get("x").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `x` to be a primitive type in the JSON string but got `%s`", jsonObj.get("x").toString()));
      }
      if ((jsonObj.get("y") != null && !jsonObj.get("y").isJsonNull()) && !jsonObj.get("y").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `y` to be a primitive type in the JSON string but got `%s`", jsonObj.get("y").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetJwksResponseKeysItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetJwksResponseKeysItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetJwksResponseKeysItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetJwksResponseKeysItem.class));

       return (TypeAdapter<T>) new TypeAdapter<GetJwksResponseKeysItem>() {
           @Override
           public void write(JsonWriter out, GetJwksResponseKeysItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetJwksResponseKeysItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetJwksResponseKeysItem given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetJwksResponseKeysItem
   * @throws IOException if the JSON string is invalid with respect to GetJwksResponseKeysItem
   */
  public static GetJwksResponseKeysItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetJwksResponseKeysItem.class);
  }

  /**
   * Convert an instance of GetJwksResponseKeysItem to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

