/*
 * LumoAuth API
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lumoauth.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.lumoauth.client.JSON;

/**
 * SmsEnrollmentStarted
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-10-07T08:41:20.679341879-07:00[America/Los_Angeles]", comments = "Generator version: 7.14.0")
public class SmsEnrollmentStarted {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  /**
   * Gets or Sets state
   */
  @JsonAdapter(StateEnum.Adapter.class)
  public enum StateEnum {
    PENDING("pending");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StateEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StateEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StateEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  @javax.annotation.Nullable
  private StateEnum state;

  public static final String SERIALIZED_NAME_MASKED_PHONE = "masked_phone";
  @SerializedName(SERIALIZED_NAME_MASKED_PHONE)
  @javax.annotation.Nullable
  private String maskedPhone;

  public static final String SERIALIZED_NAME_RESEND_AFTER = "resend_after";
  @SerializedName(SERIALIZED_NAME_RESEND_AFTER)
  @javax.annotation.Nullable
  private Integer resendAfter;

  public SmsEnrollmentStarted() {
  }

  public SmsEnrollmentStarted id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public SmsEnrollmentStarted state(@javax.annotation.Nullable StateEnum state) {
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @javax.annotation.Nullable
  public StateEnum getState() {
    return state;
  }

  public void setState(@javax.annotation.Nullable StateEnum state) {
    this.state = state;
  }


  public SmsEnrollmentStarted maskedPhone(@javax.annotation.Nullable String maskedPhone) {
    this.maskedPhone = maskedPhone;
    return this;
  }

  /**
   * Get maskedPhone
   * @return maskedPhone
   */
  @javax.annotation.Nullable
  public String getMaskedPhone() {
    return maskedPhone;
  }

  public void setMaskedPhone(@javax.annotation.Nullable String maskedPhone) {
    this.maskedPhone = maskedPhone;
  }


  public SmsEnrollmentStarted resendAfter(@javax.annotation.Nullable Integer resendAfter) {
    this.resendAfter = resendAfter;
    return this;
  }

  /**
   * Seconds until a new code may be requested
   * @return resendAfter
   */
  @javax.annotation.Nullable
  public Integer getResendAfter() {
    return resendAfter;
  }

  public void setResendAfter(@javax.annotation.Nullable Integer resendAfter) {
    this.resendAfter = resendAfter;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SmsEnrollmentStarted smsEnrollmentStarted = (SmsEnrollmentStarted) o;
    return Objects.equals(this.id, smsEnrollmentStarted.id) &&
        Objects.equals(this.state, smsEnrollmentStarted.state) &&
        Objects.equals(this.maskedPhone, smsEnrollmentStarted.maskedPhone) &&
        Objects.equals(this.resendAfter, smsEnrollmentStarted.resendAfter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, state, maskedPhone, resendAfter);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SmsEnrollmentStarted {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    maskedPhone: ").append(toIndentedString(maskedPhone)).append("\n");
    sb.append("    resendAfter: ").append(toIndentedString(resendAfter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "state", "masked_phone", "resend_after"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SmsEnrollmentStarted
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SmsEnrollmentStarted.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SmsEnrollmentStarted is not found in the empty JSON string", SmsEnrollmentStarted.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SmsEnrollmentStarted.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SmsEnrollmentStarted` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("state") != null && !jsonObj.get("state").isJsonNull()) && !jsonObj.get("state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("state").toString()));
      }
      // validate the optional field `state`
      if (jsonObj.get("state") != null && !jsonObj.get("state").isJsonNull()) {
        StateEnum.validateJsonElement(jsonObj.get("state"));
      }
      if ((jsonObj.get("masked_phone") != null && !jsonObj.get("masked_phone").isJsonNull()) && !jsonObj.get("masked_phone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `masked_phone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("masked_phone").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SmsEnrollmentStarted.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SmsEnrollmentStarted' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SmsEnrollmentStarted> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SmsEnrollmentStarted.class));

       return (TypeAdapter<T>) new TypeAdapter<SmsEnrollmentStarted>() {
           @Override
           public void write(JsonWriter out, SmsEnrollmentStarted value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SmsEnrollmentStarted read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SmsEnrollmentStarted given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SmsEnrollmentStarted
   * @throws IOException if the JSON string is invalid with respect to SmsEnrollmentStarted
   */
  public static SmsEnrollmentStarted fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SmsEnrollmentStarted.class);
  }

  /**
   * Convert an instance of SmsEnrollmentStarted to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

