/*
 * LumoAuth API
 *
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMeResponseTenant {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl GetMeResponseTenant {
    pub fn new() -> GetMeResponseTenant {
        GetMeResponseTenant {
            id: None,
            slug: None,
            name: None,
        }
    }
}

