/*
 * LumoAuth API
 *
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCurrentAgentResponse {
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<Box<models::GetCurrentAgentResponseIdentity>>,
    #[serde(rename = "capabilities", skip_serializing_if = "Option::is_none")]
    pub capabilities: Option<Vec<String>>,
    #[serde(rename = "workspace", skip_serializing_if = "Option::is_none")]
    pub workspace: Option<Box<models::GetCurrentAgentResponseWorkspace>>,
}

impl GetCurrentAgentResponse {
    pub fn new() -> GetCurrentAgentResponse {
        GetCurrentAgentResponse {
            identity: None,
            capabilities: None,
            workspace: None,
        }
    }
}

