/*
 * LumoAuth API
 *
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListPendingRequestsResponse {
    #[serde(rename = "pending_requests", skip_serializing_if = "Option::is_none")]
    pub pending_requests: Option<Vec<serde_json::Value>>,
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<serde_json::Value>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<serde_json::Value>,
}

impl ListPendingRequestsResponse {
    pub fn new() -> ListPendingRequestsResponse {
        ListPendingRequestsResponse {
            pending_requests: None,
            count: None,
            data: None,
            pagination: None,
        }
    }
}

