/*
 * LumoAuth API
 *
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpServer {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "server_id", skip_serializing_if = "Option::is_none")]
    pub server_id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "resource_uri", skip_serializing_if = "Option::is_none")]
    pub resource_uri: Option<String>,
    #[serde(rename = "endpoint_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub endpoint_url: Option<Option<String>>,
    #[serde(rename = "transport", skip_serializing_if = "Option::is_none")]
    pub transport: Option<String>,
    #[serde(rename = "auth_mode", skip_serializing_if = "Option::is_none")]
    pub auth_mode: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "scopes_supported", skip_serializing_if = "Option::is_none")]
    pub scopes_supported: Option<Vec<String>>,
    #[serde(rename = "scope_descriptions", skip_serializing_if = "Option::is_none")]
    pub scope_descriptions: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "allowed_client_ids", skip_serializing_if = "Option::is_none")]
    pub allowed_client_ids: Option<Vec<String>>,
    #[serde(rename = "require_pkce", skip_serializing_if = "Option::is_none")]
    pub require_pkce: Option<bool>,
    #[serde(rename = "require_resource_param", skip_serializing_if = "Option::is_none")]
    pub require_resource_param: Option<bool>,
    #[serde(rename = "require_dpop", skip_serializing_if = "Option::is_none")]
    pub require_dpop: Option<bool>,
    #[serde(rename = "token_lifetime", skip_serializing_if = "Option::is_none")]
    pub token_lifetime: Option<i32>,
    #[serde(rename = "posture", skip_serializing_if = "Option::is_none")]
    pub posture: Option<Box<models::McpServerPosture>>,
    #[serde(rename = "capabilities", skip_serializing_if = "Option::is_none")]
    pub capabilities: Option<Vec<String>>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

impl McpServer {
    pub fn new() -> McpServer {
        McpServer {
            id: None,
            server_id: None,
            name: None,
            description: None,
            resource_uri: None,
            endpoint_url: None,
            transport: None,
            auth_mode: None,
            status: None,
            scopes_supported: None,
            scope_descriptions: None,
            allowed_client_ids: None,
            require_pkce: None,
            require_resource_param: None,
            require_dpop: None,
            token_lifetime: None,
            posture: None,
            capabilities: None,
            created_at: None,
        }
    }
}

