/*
 * LumoAuth API
 *
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SocialLoginProvider {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "brandColor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub brand_color: Option<Option<String>>,
    #[serde(rename = "iconUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon_url: Option<Option<String>>,
    #[serde(rename = "jitProvisioningEnabled")]
    pub jit_provisioning_enabled: bool,
    /// Detailed responses only
    #[serde(rename = "clientId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<Option<String>>,
    /// Detailed responses only
    #[serde(rename = "callbackUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub callback_url: Option<Option<String>>,
    /// Detailed responses only
    #[serde(rename = "requestedScopes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub requested_scopes: Option<Option<Vec<String>>>,
    /// Detailed responses only
    #[serde(rename = "customClaims", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_claims: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    /// Detailed responses only
    #[serde(rename = "claimMapping", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub claim_mapping: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    /// Detailed responses only; secrets redacted
    #[serde(rename = "providerConfig", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub provider_config: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    /// Detailed responses only
    #[serde(rename = "authorizationUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub authorization_url: Option<Option<String>>,
    /// Detailed responses only
    #[serde(rename = "tokenUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub token_url: Option<Option<String>>,
    /// Detailed responses only
    #[serde(rename = "userInfoUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_info_url: Option<Option<String>>,
    /// Detailed responses only
    #[serde(rename = "defaultRoles", skip_serializing_if = "Option::is_none")]
    pub default_roles: Option<Vec<models::RoleRef>>,
}

impl SocialLoginProvider {
    pub fn new(id: i32, provider: String, display_name: String, enabled: bool, jit_provisioning_enabled: bool) -> SocialLoginProvider {
        SocialLoginProvider {
            id,
            provider,
            display_name,
            enabled,
            brand_color: None,
            icon_url: None,
            jit_provisioning_enabled,
            client_id: None,
            callback_url: None,
            requested_scopes: None,
            custom_claims: None,
            claim_mapping: None,
            provider_config: None,
            authorization_url: None,
            token_url: None,
            user_info_url: None,
            default_roles: None,
        }
    }
}

