/*
 * LumoAuth API
 *
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TotpEnrollmentStarted {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
    #[serde(rename = "otpauth_uri", skip_serializing_if = "Option::is_none")]
    pub otpauth_uri: Option<String>,
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    #[serde(rename = "secret_grouped", skip_serializing_if = "Option::is_none")]
    pub secret_grouped: Option<String>,
    #[serde(rename = "qr_data_uri", skip_serializing_if = "Option::is_none")]
    pub qr_data_uri: Option<String>,
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
}

impl TotpEnrollmentStarted {
    pub fn new() -> TotpEnrollmentStarted {
        TotpEnrollmentStarted {
            id: None,
            state: None,
            otpauth_uri: None,
            secret: None,
            secret_grouped: None,
            qr_data_uri: None,
            expires_at: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "pending")]
    Pending,
}

impl Default for State {
    fn default() -> State {
        Self::Pending
    }
}

