/* tslint:disable */
/* eslint-disable */
/**
 * LumoAuth API
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdminAgentsGenerateTokenRequest
 */
export interface AdminAgentsGenerateTokenRequest {
    /**
     * Optional scopes to embed in the token.
     * @type {Array<string>}
     * @memberof AdminAgentsGenerateTokenRequest
     */
    'scopes'?: Array<string>;
    /**
     * Optional token lifetime in seconds.
     * @type {number}
     * @memberof AdminAgentsGenerateTokenRequest
     */
    'ttl'?: number;
}

