/* tslint:disable */
/* eslint-disable */
/**
 * LumoAuth API
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Organization name plus the raw settings dictionary: any stored key (display_name, timezone, locale, security, email, audit_log_retention_days, audit_log_auto_delete, agent_governance, ...) is returned as-is; secret-looking keys are redacted.
 * @export
 * @interface AdminSettingsAllResponseDataGeneral
 */
export interface AdminSettingsAllResponseDataGeneral {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof AdminSettingsAllResponseDataGeneral
     */
    'name'?: string;
}

