/* tslint:disable */
/* eslint-disable */
/**
 * LumoAuth API
 * LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sdk@lumoauth.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AgentOutboundConnection } from './agent-outbound-connection';
// May contain unused imports in some cases
// @ts-ignore
import type { ListConnectionsResponseAgent } from './list-connections-response-agent';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

/**
 * 
 * @export
 * @interface ListConnectionsResponse
 */
export interface ListConnectionsResponse {
    /**
     * 
     * @type {ListConnectionsResponseAgent}
     * @memberof ListConnectionsResponse
     */
    'agent': ListConnectionsResponseAgent;
    /**
     * 
     * @type {Array<AgentOutboundConnection>}
     * @memberof ListConnectionsResponse
     */
    'connections': Array<AgentOutboundConnection>;
    /**
     * Same items as connections.
     * @type {Array<{ [key: string]: any; }>}
     * @memberof ListConnectionsResponse
     */
    'data': Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof ListConnectionsResponse
     */
    'pagination': PaginationMeta;
}

