//
// AdminAuditLogsRetentionResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdminAuditLogsRetentionResponseData: Codable, JSONEncodable, Hashable {

    /** Effective retention, capped by the plan limit */
    public var retentionDays: Int?
    public var autoDelete: Bool?
    /** Plan cap; null when unlimited or billing enforcement is off */
    public var planLimitDays: Int?

    public init(retentionDays: Int? = nil, autoDelete: Bool? = nil, planLimitDays: Int? = nil) {
        self.retentionDays = retentionDays
        self.autoDelete = autoDelete
        self.planLimitDays = planLimitDays
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case retentionDays
        case autoDelete
        case planLimitDays
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(retentionDays, forKey: .retentionDays)
        try container.encodeIfPresent(autoDelete, forKey: .autoDelete)
        try container.encodeIfPresent(planLimitDays, forKey: .planLimitDays)
    }
}

