//
// EnrollAuthenticator201Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum EnrollAuthenticator201Response: Codable, JSONEncodable, Hashable {
    case typeEmailEnrollmentStarted(EmailEnrollmentStarted)
    case typePasskeyEnrollmentStarted(PasskeyEnrollmentStarted)
    case typePushEnrollmentStarted(PushEnrollmentStarted)
    case typeSmsEnrollmentStarted(SmsEnrollmentStarted)
    case typeTotpEnrollmentStarted(TotpEnrollmentStarted)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeEmailEnrollmentStarted(let value):
            try container.encode(value)
        case .typePasskeyEnrollmentStarted(let value):
            try container.encode(value)
        case .typePushEnrollmentStarted(let value):
            try container.encode(value)
        case .typeSmsEnrollmentStarted(let value):
            try container.encode(value)
        case .typeTotpEnrollmentStarted(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(EmailEnrollmentStarted.self) {
            self = .typeEmailEnrollmentStarted(value)
        } else if let value = try? container.decode(PasskeyEnrollmentStarted.self) {
            self = .typePasskeyEnrollmentStarted(value)
        } else if let value = try? container.decode(PushEnrollmentStarted.self) {
            self = .typePushEnrollmentStarted(value)
        } else if let value = try? container.decode(SmsEnrollmentStarted.self) {
            self = .typeSmsEnrollmentStarted(value)
        } else if let value = try? container.decode(TotpEnrollmentStarted.self) {
            self = .typeTotpEnrollmentStarted(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of EnrollAuthenticator201Response"))
        }
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension EnrollAuthenticator201Response: Identifiable {}
