//
// McpServer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct McpServer: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var serverId: String?
    public var name: String?
    public var description: String?
    public var resourceUri: String?
    public var endpointUrl: String?
    public var transport: String?
    public var authMode: String?
    public var status: String?
    public var scopesSupported: [String]?
    public var scopeDescriptions: [String: String]?
    public var allowedClientIds: [String]?
    public var requirePkce: Bool?
    public var requireResourceParam: Bool?
    public var requireDpop: Bool?
    public var tokenLifetime: Int?
    public var posture: McpServerPosture?
    public var capabilities: [String]?
    public var createdAt: Date?

    public init(id: Int? = nil, serverId: String? = nil, name: String? = nil, description: String? = nil, resourceUri: String? = nil, endpointUrl: String? = nil, transport: String? = nil, authMode: String? = nil, status: String? = nil, scopesSupported: [String]? = nil, scopeDescriptions: [String: String]? = nil, allowedClientIds: [String]? = nil, requirePkce: Bool? = nil, requireResourceParam: Bool? = nil, requireDpop: Bool? = nil, tokenLifetime: Int? = nil, posture: McpServerPosture? = nil, capabilities: [String]? = nil, createdAt: Date? = nil) {
        self.id = id
        self.serverId = serverId
        self.name = name
        self.description = description
        self.resourceUri = resourceUri
        self.endpointUrl = endpointUrl
        self.transport = transport
        self.authMode = authMode
        self.status = status
        self.scopesSupported = scopesSupported
        self.scopeDescriptions = scopeDescriptions
        self.allowedClientIds = allowedClientIds
        self.requirePkce = requirePkce
        self.requireResourceParam = requireResourceParam
        self.requireDpop = requireDpop
        self.tokenLifetime = tokenLifetime
        self.posture = posture
        self.capabilities = capabilities
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case serverId = "server_id"
        case name
        case description
        case resourceUri = "resource_uri"
        case endpointUrl = "endpoint_url"
        case transport
        case authMode = "auth_mode"
        case status
        case scopesSupported = "scopes_supported"
        case scopeDescriptions = "scope_descriptions"
        case allowedClientIds = "allowed_client_ids"
        case requirePkce = "require_pkce"
        case requireResourceParam = "require_resource_param"
        case requireDpop = "require_dpop"
        case tokenLifetime = "token_lifetime"
        case posture
        case capabilities
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(serverId, forKey: .serverId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(resourceUri, forKey: .resourceUri)
        try container.encodeIfPresent(endpointUrl, forKey: .endpointUrl)
        try container.encodeIfPresent(transport, forKey: .transport)
        try container.encodeIfPresent(authMode, forKey: .authMode)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(scopesSupported, forKey: .scopesSupported)
        try container.encodeIfPresent(scopeDescriptions, forKey: .scopeDescriptions)
        try container.encodeIfPresent(allowedClientIds, forKey: .allowedClientIds)
        try container.encodeIfPresent(requirePkce, forKey: .requirePkce)
        try container.encodeIfPresent(requireResourceParam, forKey: .requireResourceParam)
        try container.encodeIfPresent(requireDpop, forKey: .requireDpop)
        try container.encodeIfPresent(tokenLifetime, forKey: .tokenLifetime)
        try container.encodeIfPresent(posture, forKey: .posture)
        try container.encodeIfPresent(capabilities, forKey: .capabilities)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension McpServer: Identifiable {}
