//
// PasskeyEnrollmentStarted.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PasskeyEnrollmentStarted: Codable, JSONEncodable, Hashable {

    public enum Id: String, Codable, CaseIterable {
        case passkeyPending = "passkey:pending"
    }
    public enum State: String, Codable, CaseIterable {
        case pending = "pending"
    }
    public var id: Id?
    public var state: State?
    /** WebAuthn PublicKeyCredentialCreationOptions */
    public var publicKey: AnyCodable?

    public init(id: Id? = nil, state: State? = nil, publicKey: AnyCodable? = nil) {
        self.id = id
        self.state = state
        self.publicKey = publicKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case state
        case publicKey = "public_key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(publicKey, forKey: .publicKey)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PasskeyEnrollmentStarted: Identifiable {}
