/*
LumoAuth API

LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 

API version: 1.0.0
Contact: sdk@lumoauth.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lumoauthclient

import (
	"encoding/json"
)

// checks if the RemoveUserGroupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoveUserGroupResponse{}

// RemoveUserGroupResponse struct for RemoveUserGroupResponse
type RemoveUserGroupResponse struct {
	Data *User `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewRemoveUserGroupResponse instantiates a new RemoveUserGroupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoveUserGroupResponse() *RemoveUserGroupResponse {
	this := RemoveUserGroupResponse{}
	return &this
}

// NewRemoveUserGroupResponseWithDefaults instantiates a new RemoveUserGroupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoveUserGroupResponseWithDefaults() *RemoveUserGroupResponse {
	this := RemoveUserGroupResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *RemoveUserGroupResponse) GetData() User {
	if o == nil || IsNil(o.Data) {
		var ret User
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoveUserGroupResponse) GetDataOk() (*User, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *RemoveUserGroupResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given User and assigns it to the Data field.
func (o *RemoveUserGroupResponse) SetData(v User) {
	o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *RemoveUserGroupResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoveUserGroupResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *RemoveUserGroupResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *RemoveUserGroupResponse) SetMessage(v string) {
	o.Message = &v
}

func (o RemoveUserGroupResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoveUserGroupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableRemoveUserGroupResponse struct {
	value *RemoveUserGroupResponse
	isSet bool
}

func (v NullableRemoveUserGroupResponse) Get() *RemoveUserGroupResponse {
	return v.value
}

func (v *NullableRemoveUserGroupResponse) Set(val *RemoveUserGroupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoveUserGroupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoveUserGroupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoveUserGroupResponse(val *RemoveUserGroupResponse) *NullableRemoveUserGroupResponse {
	return &NullableRemoveUserGroupResponse{value: val, isSet: true}
}

func (v NullableRemoveUserGroupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoveUserGroupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


