/*
LumoAuth API

LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 

API version: 1.0.0
Contact: sdk@lumoauth.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lumoauthclient

import (
	"encoding/json"
)

// checks if the AdminWebhooksTunnelStartResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminWebhooksTunnelStartResponse{}

// AdminWebhooksTunnelStartResponse struct for AdminWebhooksTunnelStartResponse
type AdminWebhooksTunnelStartResponse struct {
	Data *AdminWebhooksTunnelStartResponseData `json:"data,omitempty"`
}

// NewAdminWebhooksTunnelStartResponse instantiates a new AdminWebhooksTunnelStartResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminWebhooksTunnelStartResponse() *AdminWebhooksTunnelStartResponse {
	this := AdminWebhooksTunnelStartResponse{}
	return &this
}

// NewAdminWebhooksTunnelStartResponseWithDefaults instantiates a new AdminWebhooksTunnelStartResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminWebhooksTunnelStartResponseWithDefaults() *AdminWebhooksTunnelStartResponse {
	this := AdminWebhooksTunnelStartResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AdminWebhooksTunnelStartResponse) GetData() AdminWebhooksTunnelStartResponseData {
	if o == nil || IsNil(o.Data) {
		var ret AdminWebhooksTunnelStartResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminWebhooksTunnelStartResponse) GetDataOk() (*AdminWebhooksTunnelStartResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AdminWebhooksTunnelStartResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given AdminWebhooksTunnelStartResponseData and assigns it to the Data field.
func (o *AdminWebhooksTunnelStartResponse) SetData(v AdminWebhooksTunnelStartResponseData) {
	o.Data = &v
}

func (o AdminWebhooksTunnelStartResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminWebhooksTunnelStartResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableAdminWebhooksTunnelStartResponse struct {
	value *AdminWebhooksTunnelStartResponse
	isSet bool
}

func (v NullableAdminWebhooksTunnelStartResponse) Get() *AdminWebhooksTunnelStartResponse {
	return v.value
}

func (v *NullableAdminWebhooksTunnelStartResponse) Set(val *AdminWebhooksTunnelStartResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminWebhooksTunnelStartResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminWebhooksTunnelStartResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminWebhooksTunnelStartResponse(val *AdminWebhooksTunnelStartResponse) *NullableAdminWebhooksTunnelStartResponse {
	return &NullableAdminWebhooksTunnelStartResponse{value: val, isSet: true}
}

func (v NullableAdminWebhooksTunnelStartResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminWebhooksTunnelStartResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


