/*
LumoAuth API

LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 

API version: 1.0.0
Contact: sdk@lumoauth.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lumoauthclient

import (
	"encoding/json"
	"time"
)

// checks if the PushEnrollmentStarted type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PushEnrollmentStarted{}

// PushEnrollmentStarted struct for PushEnrollmentStarted
type PushEnrollmentStarted struct {
	Id *string `json:"id,omitempty"`
	State *string `json:"state,omitempty"`
	QrDataUri *string `json:"qr_data_uri,omitempty"`
	DeepLink *string `json:"deep_link,omitempty"`
	ActivationCode *string `json:"activation_code,omitempty"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
}

// NewPushEnrollmentStarted instantiates a new PushEnrollmentStarted object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPushEnrollmentStarted() *PushEnrollmentStarted {
	this := PushEnrollmentStarted{}
	return &this
}

// NewPushEnrollmentStartedWithDefaults instantiates a new PushEnrollmentStarted object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPushEnrollmentStartedWithDefaults() *PushEnrollmentStarted {
	this := PushEnrollmentStarted{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PushEnrollmentStarted) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushEnrollmentStarted) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PushEnrollmentStarted) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PushEnrollmentStarted) SetId(v string) {
	o.Id = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *PushEnrollmentStarted) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushEnrollmentStarted) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *PushEnrollmentStarted) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *PushEnrollmentStarted) SetState(v string) {
	o.State = &v
}

// GetQrDataUri returns the QrDataUri field value if set, zero value otherwise.
func (o *PushEnrollmentStarted) GetQrDataUri() string {
	if o == nil || IsNil(o.QrDataUri) {
		var ret string
		return ret
	}
	return *o.QrDataUri
}

// GetQrDataUriOk returns a tuple with the QrDataUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushEnrollmentStarted) GetQrDataUriOk() (*string, bool) {
	if o == nil || IsNil(o.QrDataUri) {
		return nil, false
	}
	return o.QrDataUri, true
}

// HasQrDataUri returns a boolean if a field has been set.
func (o *PushEnrollmentStarted) HasQrDataUri() bool {
	if o != nil && !IsNil(o.QrDataUri) {
		return true
	}

	return false
}

// SetQrDataUri gets a reference to the given string and assigns it to the QrDataUri field.
func (o *PushEnrollmentStarted) SetQrDataUri(v string) {
	o.QrDataUri = &v
}

// GetDeepLink returns the DeepLink field value if set, zero value otherwise.
func (o *PushEnrollmentStarted) GetDeepLink() string {
	if o == nil || IsNil(o.DeepLink) {
		var ret string
		return ret
	}
	return *o.DeepLink
}

// GetDeepLinkOk returns a tuple with the DeepLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushEnrollmentStarted) GetDeepLinkOk() (*string, bool) {
	if o == nil || IsNil(o.DeepLink) {
		return nil, false
	}
	return o.DeepLink, true
}

// HasDeepLink returns a boolean if a field has been set.
func (o *PushEnrollmentStarted) HasDeepLink() bool {
	if o != nil && !IsNil(o.DeepLink) {
		return true
	}

	return false
}

// SetDeepLink gets a reference to the given string and assigns it to the DeepLink field.
func (o *PushEnrollmentStarted) SetDeepLink(v string) {
	o.DeepLink = &v
}

// GetActivationCode returns the ActivationCode field value if set, zero value otherwise.
func (o *PushEnrollmentStarted) GetActivationCode() string {
	if o == nil || IsNil(o.ActivationCode) {
		var ret string
		return ret
	}
	return *o.ActivationCode
}

// GetActivationCodeOk returns a tuple with the ActivationCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushEnrollmentStarted) GetActivationCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ActivationCode) {
		return nil, false
	}
	return o.ActivationCode, true
}

// HasActivationCode returns a boolean if a field has been set.
func (o *PushEnrollmentStarted) HasActivationCode() bool {
	if o != nil && !IsNil(o.ActivationCode) {
		return true
	}

	return false
}

// SetActivationCode gets a reference to the given string and assigns it to the ActivationCode field.
func (o *PushEnrollmentStarted) SetActivationCode(v string) {
	o.ActivationCode = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *PushEnrollmentStarted) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushEnrollmentStarted) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *PushEnrollmentStarted) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *PushEnrollmentStarted) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

func (o PushEnrollmentStarted) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PushEnrollmentStarted) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.QrDataUri) {
		toSerialize["qr_data_uri"] = o.QrDataUri
	}
	if !IsNil(o.DeepLink) {
		toSerialize["deep_link"] = o.DeepLink
	}
	if !IsNil(o.ActivationCode) {
		toSerialize["activation_code"] = o.ActivationCode
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	return toSerialize, nil
}

type NullablePushEnrollmentStarted struct {
	value *PushEnrollmentStarted
	isSet bool
}

func (v NullablePushEnrollmentStarted) Get() *PushEnrollmentStarted {
	return v.value
}

func (v *NullablePushEnrollmentStarted) Set(val *PushEnrollmentStarted) {
	v.value = val
	v.isSet = true
}

func (v NullablePushEnrollmentStarted) IsSet() bool {
	return v.isSet
}

func (v *NullablePushEnrollmentStarted) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePushEnrollmentStarted(val *PushEnrollmentStarted) *NullablePushEnrollmentStarted {
	return &NullablePushEnrollmentStarted{value: val, isSet: true}
}

func (v NullablePushEnrollmentStarted) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePushEnrollmentStarted) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


