/*
LumoAuth API

LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 

API version: 1.0.0
Contact: sdk@lumoauth.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lumoauthclient

import (
	"encoding/json"
	"time"
)

// checks if the IssueTemporaryAccessCodeResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IssueTemporaryAccessCodeResponseData{}

// IssueTemporaryAccessCodeResponseData struct for IssueTemporaryAccessCodeResponseData
type IssueTemporaryAccessCodeResponseData struct {
	Id *string `json:"id,omitempty"`
	Code *string `json:"code,omitempty"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	SingleUse *bool `json:"single_use,omitempty"`
}

// NewIssueTemporaryAccessCodeResponseData instantiates a new IssueTemporaryAccessCodeResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIssueTemporaryAccessCodeResponseData() *IssueTemporaryAccessCodeResponseData {
	this := IssueTemporaryAccessCodeResponseData{}
	return &this
}

// NewIssueTemporaryAccessCodeResponseDataWithDefaults instantiates a new IssueTemporaryAccessCodeResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIssueTemporaryAccessCodeResponseDataWithDefaults() *IssueTemporaryAccessCodeResponseData {
	this := IssueTemporaryAccessCodeResponseData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IssueTemporaryAccessCodeResponseData) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssueTemporaryAccessCodeResponseData) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IssueTemporaryAccessCodeResponseData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *IssueTemporaryAccessCodeResponseData) SetId(v string) {
	o.Id = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *IssueTemporaryAccessCodeResponseData) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssueTemporaryAccessCodeResponseData) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *IssueTemporaryAccessCodeResponseData) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *IssueTemporaryAccessCodeResponseData) SetCode(v string) {
	o.Code = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *IssueTemporaryAccessCodeResponseData) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssueTemporaryAccessCodeResponseData) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *IssueTemporaryAccessCodeResponseData) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *IssueTemporaryAccessCodeResponseData) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetSingleUse returns the SingleUse field value if set, zero value otherwise.
func (o *IssueTemporaryAccessCodeResponseData) GetSingleUse() bool {
	if o == nil || IsNil(o.SingleUse) {
		var ret bool
		return ret
	}
	return *o.SingleUse
}

// GetSingleUseOk returns a tuple with the SingleUse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssueTemporaryAccessCodeResponseData) GetSingleUseOk() (*bool, bool) {
	if o == nil || IsNil(o.SingleUse) {
		return nil, false
	}
	return o.SingleUse, true
}

// HasSingleUse returns a boolean if a field has been set.
func (o *IssueTemporaryAccessCodeResponseData) HasSingleUse() bool {
	if o != nil && !IsNil(o.SingleUse) {
		return true
	}

	return false
}

// SetSingleUse gets a reference to the given bool and assigns it to the SingleUse field.
func (o *IssueTemporaryAccessCodeResponseData) SetSingleUse(v bool) {
	o.SingleUse = &v
}

func (o IssueTemporaryAccessCodeResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IssueTemporaryAccessCodeResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	if !IsNil(o.SingleUse) {
		toSerialize["single_use"] = o.SingleUse
	}
	return toSerialize, nil
}

type NullableIssueTemporaryAccessCodeResponseData struct {
	value *IssueTemporaryAccessCodeResponseData
	isSet bool
}

func (v NullableIssueTemporaryAccessCodeResponseData) Get() *IssueTemporaryAccessCodeResponseData {
	return v.value
}

func (v *NullableIssueTemporaryAccessCodeResponseData) Set(val *IssueTemporaryAccessCodeResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableIssueTemporaryAccessCodeResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableIssueTemporaryAccessCodeResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIssueTemporaryAccessCodeResponseData(val *IssueTemporaryAccessCodeResponseData) *NullableIssueTemporaryAccessCodeResponseData {
	return &NullableIssueTemporaryAccessCodeResponseData{value: val, isSet: true}
}

func (v NullableIssueTemporaryAccessCodeResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIssueTemporaryAccessCodeResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


