/*
LumoAuth API

LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 

API version: 1.0.0
Contact: sdk@lumoauth.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lumoauthclient

import (
	"encoding/json"
)

// checks if the VerifyAgentCardResponseSigner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyAgentCardResponseSigner{}

// VerifyAgentCardResponseSigner Only when valid=true.
type VerifyAgentCardResponseSigner struct {
	Kid NullableString `json:"kid,omitempty"`
	Alg NullableString `json:"alg,omitempty"`
}

// NewVerifyAgentCardResponseSigner instantiates a new VerifyAgentCardResponseSigner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyAgentCardResponseSigner() *VerifyAgentCardResponseSigner {
	this := VerifyAgentCardResponseSigner{}
	return &this
}

// NewVerifyAgentCardResponseSignerWithDefaults instantiates a new VerifyAgentCardResponseSigner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyAgentCardResponseSignerWithDefaults() *VerifyAgentCardResponseSigner {
	this := VerifyAgentCardResponseSigner{}
	return &this
}

// GetKid returns the Kid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerifyAgentCardResponseSigner) GetKid() string {
	if o == nil || IsNil(o.Kid.Get()) {
		var ret string
		return ret
	}
	return *o.Kid.Get()
}

// GetKidOk returns a tuple with the Kid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerifyAgentCardResponseSigner) GetKidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Kid.Get(), o.Kid.IsSet()
}

// HasKid returns a boolean if a field has been set.
func (o *VerifyAgentCardResponseSigner) HasKid() bool {
	if o != nil && o.Kid.IsSet() {
		return true
	}

	return false
}

// SetKid gets a reference to the given NullableString and assigns it to the Kid field.
func (o *VerifyAgentCardResponseSigner) SetKid(v string) {
	o.Kid.Set(&v)
}
// SetKidNil sets the value for Kid to be an explicit nil
func (o *VerifyAgentCardResponseSigner) SetKidNil() {
	o.Kid.Set(nil)
}

// UnsetKid ensures that no value is present for Kid, not even an explicit nil
func (o *VerifyAgentCardResponseSigner) UnsetKid() {
	o.Kid.Unset()
}

// GetAlg returns the Alg field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerifyAgentCardResponseSigner) GetAlg() string {
	if o == nil || IsNil(o.Alg.Get()) {
		var ret string
		return ret
	}
	return *o.Alg.Get()
}

// GetAlgOk returns a tuple with the Alg field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerifyAgentCardResponseSigner) GetAlgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Alg.Get(), o.Alg.IsSet()
}

// HasAlg returns a boolean if a field has been set.
func (o *VerifyAgentCardResponseSigner) HasAlg() bool {
	if o != nil && o.Alg.IsSet() {
		return true
	}

	return false
}

// SetAlg gets a reference to the given NullableString and assigns it to the Alg field.
func (o *VerifyAgentCardResponseSigner) SetAlg(v string) {
	o.Alg.Set(&v)
}
// SetAlgNil sets the value for Alg to be an explicit nil
func (o *VerifyAgentCardResponseSigner) SetAlgNil() {
	o.Alg.Set(nil)
}

// UnsetAlg ensures that no value is present for Alg, not even an explicit nil
func (o *VerifyAgentCardResponseSigner) UnsetAlg() {
	o.Alg.Unset()
}

func (o VerifyAgentCardResponseSigner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyAgentCardResponseSigner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Kid.IsSet() {
		toSerialize["kid"] = o.Kid.Get()
	}
	if o.Alg.IsSet() {
		toSerialize["alg"] = o.Alg.Get()
	}
	return toSerialize, nil
}

type NullableVerifyAgentCardResponseSigner struct {
	value *VerifyAgentCardResponseSigner
	isSet bool
}

func (v NullableVerifyAgentCardResponseSigner) Get() *VerifyAgentCardResponseSigner {
	return v.value
}

func (v *NullableVerifyAgentCardResponseSigner) Set(val *VerifyAgentCardResponseSigner) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyAgentCardResponseSigner) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyAgentCardResponseSigner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyAgentCardResponseSigner(val *VerifyAgentCardResponseSigner) *NullableVerifyAgentCardResponseSigner {
	return &NullableVerifyAgentCardResponseSigner{value: val, isSet: true}
}

func (v NullableVerifyAgentCardResponseSigner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyAgentCardResponseSigner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


