/*
LumoAuth API

LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 

API version: 1.0.0
Contact: sdk@lumoauth.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lumoauthclient

import (
	"encoding/json"
)

// checks if the AdminPermissionsGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminPermissionsGetResponse{}

// AdminPermissionsGetResponse struct for AdminPermissionsGetResponse
type AdminPermissionsGetResponse struct {
	Data *Permission `json:"data,omitempty"`
}

// NewAdminPermissionsGetResponse instantiates a new AdminPermissionsGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminPermissionsGetResponse() *AdminPermissionsGetResponse {
	this := AdminPermissionsGetResponse{}
	return &this
}

// NewAdminPermissionsGetResponseWithDefaults instantiates a new AdminPermissionsGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminPermissionsGetResponseWithDefaults() *AdminPermissionsGetResponse {
	this := AdminPermissionsGetResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AdminPermissionsGetResponse) GetData() Permission {
	if o == nil || IsNil(o.Data) {
		var ret Permission
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminPermissionsGetResponse) GetDataOk() (*Permission, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AdminPermissionsGetResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given Permission and assigns it to the Data field.
func (o *AdminPermissionsGetResponse) SetData(v Permission) {
	o.Data = &v
}

func (o AdminPermissionsGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminPermissionsGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableAdminPermissionsGetResponse struct {
	value *AdminPermissionsGetResponse
	isSet bool
}

func (v NullableAdminPermissionsGetResponse) Get() *AdminPermissionsGetResponse {
	return v.value
}

func (v *NullableAdminPermissionsGetResponse) Set(val *AdminPermissionsGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminPermissionsGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminPermissionsGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminPermissionsGetResponse(val *AdminPermissionsGetResponse) *NullableAdminPermissionsGetResponse {
	return &NullableAdminPermissionsGetResponse{value: val, isSet: true}
}

func (v NullableAdminPermissionsGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminPermissionsGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


