/*
LumoAuth API

LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 

API version: 1.0.0
Contact: sdk@lumoauth.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lumoauthclient

import (
	"encoding/json"
)

// checks if the PutAdminSettingsEmailUpdateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutAdminSettingsEmailUpdateResponse{}

// PutAdminSettingsEmailUpdateResponse struct for PutAdminSettingsEmailUpdateResponse
type PutAdminSettingsEmailUpdateResponse struct {
	// Free-form email settings dictionary, stored as sent (keys merge on update); secret-looking keys are redacted.
	Data map[string]interface{} `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewPutAdminSettingsEmailUpdateResponse instantiates a new PutAdminSettingsEmailUpdateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutAdminSettingsEmailUpdateResponse() *PutAdminSettingsEmailUpdateResponse {
	this := PutAdminSettingsEmailUpdateResponse{}
	return &this
}

// NewPutAdminSettingsEmailUpdateResponseWithDefaults instantiates a new PutAdminSettingsEmailUpdateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutAdminSettingsEmailUpdateResponseWithDefaults() *PutAdminSettingsEmailUpdateResponse {
	this := PutAdminSettingsEmailUpdateResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PutAdminSettingsEmailUpdateResponse) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutAdminSettingsEmailUpdateResponse) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PutAdminSettingsEmailUpdateResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *PutAdminSettingsEmailUpdateResponse) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *PutAdminSettingsEmailUpdateResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutAdminSettingsEmailUpdateResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *PutAdminSettingsEmailUpdateResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *PutAdminSettingsEmailUpdateResponse) SetMessage(v string) {
	o.Message = &v
}

func (o PutAdminSettingsEmailUpdateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutAdminSettingsEmailUpdateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullablePutAdminSettingsEmailUpdateResponse struct {
	value *PutAdminSettingsEmailUpdateResponse
	isSet bool
}

func (v NullablePutAdminSettingsEmailUpdateResponse) Get() *PutAdminSettingsEmailUpdateResponse {
	return v.value
}

func (v *NullablePutAdminSettingsEmailUpdateResponse) Set(val *PutAdminSettingsEmailUpdateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePutAdminSettingsEmailUpdateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePutAdminSettingsEmailUpdateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutAdminSettingsEmailUpdateResponse(val *PutAdminSettingsEmailUpdateResponse) *NullablePutAdminSettingsEmailUpdateResponse {
	return &NullablePutAdminSettingsEmailUpdateResponse{value: val, isSet: true}
}

func (v NullablePutAdminSettingsEmailUpdateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutAdminSettingsEmailUpdateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


