/*
LumoAuth API

LumoAuth REST API — authentication, authorization, agent registry, MCP server authorization, and tenant administration. Multi-tenant: most paths are scoped under `/orgs/{orgId}/api/v1/...`. 

API version: 1.0.0
Contact: sdk@lumoauth.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lumoauthclient

import (
	"encoding/json"
)

// checks if the CheckAbacBulkResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckAbacBulkResponse{}

// CheckAbacBulkResponse struct for CheckAbacBulkResponse
type CheckAbacBulkResponse struct {
	Results []CheckAbacBulkResponseResultsItem `json:"results,omitempty"`
	UserId *string `json:"user_id,omitempty"`
}

// NewCheckAbacBulkResponse instantiates a new CheckAbacBulkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckAbacBulkResponse() *CheckAbacBulkResponse {
	this := CheckAbacBulkResponse{}
	return &this
}

// NewCheckAbacBulkResponseWithDefaults instantiates a new CheckAbacBulkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckAbacBulkResponseWithDefaults() *CheckAbacBulkResponse {
	this := CheckAbacBulkResponse{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *CheckAbacBulkResponse) GetResults() []CheckAbacBulkResponseResultsItem {
	if o == nil || IsNil(o.Results) {
		var ret []CheckAbacBulkResponseResultsItem
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckAbacBulkResponse) GetResultsOk() ([]CheckAbacBulkResponseResultsItem, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *CheckAbacBulkResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []CheckAbacBulkResponseResultsItem and assigns it to the Results field.
func (o *CheckAbacBulkResponse) SetResults(v []CheckAbacBulkResponseResultsItem) {
	o.Results = v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *CheckAbacBulkResponse) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckAbacBulkResponse) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *CheckAbacBulkResponse) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *CheckAbacBulkResponse) SetUserId(v string) {
	o.UserId = &v
}

func (o CheckAbacBulkResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckAbacBulkResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	return toSerialize, nil
}

type NullableCheckAbacBulkResponse struct {
	value *CheckAbacBulkResponse
	isSet bool
}

func (v NullableCheckAbacBulkResponse) Get() *CheckAbacBulkResponse {
	return v.value
}

func (v *NullableCheckAbacBulkResponse) Set(val *CheckAbacBulkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckAbacBulkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckAbacBulkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckAbacBulkResponse(val *CheckAbacBulkResponse) *NullableCheckAbacBulkResponse {
	return &NullableCheckAbacBulkResponse{value: val, isSet: true}
}

func (v NullableCheckAbacBulkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckAbacBulkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


